import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, Home, CheckCircle, Award, HelpCircle, Building, TrendingUp } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const RealEstateInvestment: React.FC = () => {
  const faqData = [
    { question: "Should I invest in real estate in India?", answer: "Pros: (1) Tangible asset, (2) Rental income (3-7%), (3) Capital appreciation (5-8%/year), (4) Leverage (70-80% home loan), (5) Hedge against inflation. Cons: (1) High entry cost (₹50L+), (2) Low liquidity (takes 6-12 months to sell), (3) High transaction costs (7-10% stamp duty + brokerage), (4) Maintenance hassles, (5) Legal risks. Invest if: (1) Have ₹50L+ corpus, (2) Long-term horizon (10+ years), (3) Can handle illiquidity. Otherwise: REITs better (₹10K minimum, liquid)!" },
    { question: "Residential vs Commercial property: which gives better returns?", answer: "Commercial WINS on rental yield! Residential: 2-3% rental yield (₹1Cr property = ₹2.5L/year rent). Commercial: 6-9% rental yield (₹1Cr = ₹7L/year rent!). But: (1) Commercial needs ₹1Cr+ investment, (2) Finding tenant harder, (3) Vacancy risk higher, (4) Lease 3-9 years (locked in). Capital appreciation: Both similar (5-8%/year). Best for HNI: Commercial. Middle class: Residential or REITs!" },
    { question: "What are REITs and how to invest?", answer: "REIT (Real Estate Investment Trust) = Own commercial property via stock exchange! Min investment: ₹10,000. Top REITs: Embassy Office Parks (₹350/unit), Mindspace (₹290), Brookfield (₹280). Returns: 5-7% dividend yield + capital appreciation. Tax: 10% on dividends. Pros: (1) Low entry barrier, (2) Liquid (sell on NSE), (3) Professional management, (4) Diversified (10-20 properties). Buy on: Zerodha, Groww like stocks!" },
    { question: "What is rental yield and how to calculate?", answer: "Rental yield = (Annual rent / Property value) × 100. Example: ₹1Cr property, ₹25K/month rent → Annual rent ₹3L → Yield = 3%. Good yield: Residential 3-4%, Commercial 6-9%. Tier 1 cities (Mumbai, Delhi): 2-3%. Tier 2 (Pune, Ahmedabad): 3-5%. Tier 3: 4-6%. Lower yield in expensive cities (capital appreciation compensates)!" },
    { question: "What are all costs when buying property?", answer: "Total cost = Property price + 10-12% extra! Breakdown: (1) Stamp duty: 5-7% (varies by state, 1-2% for women in some states), (2) Registration: 1%, (3) GST: 12% on under-construction (1% on affordable housing), (4) Brokerage: 1-2%, (5) Legal fees: ₹25-50K, (6) Home loan processing: 0.5-1%, (7) Interior/furnishing: 10-15% of property value. Example: ₹1Cr property → Total outflow ₹1.12Cr!" },
    { question: "Should I take home loan or pay cash?", answer: "Take HOME LOAN if: (1) Interest rate under 9%, (2) Can invest cash elsewhere at 12%+ (equity), (3) Get 80C + Section 24 tax benefit (save ₹1.5L/year!), (4) Leverage (₹30L cash can buy ₹1Cr property). Pay cash if: (1) Interest rate above 10%, (2) Nearing retirement (don't want EMI burden), (3) Low risk appetite. Optimal: 60-70% loan (leverage benefits) + 30-40% down payment (lower EMI)." },
    { question: "What is property appreciation rate in India?", answer: "Historical: 5-8% annually (varies widely by location!). Tier 1 cities: 6-8%. Tier 2: 8-12%. Under-developed areas: 10-15% (risky - may not appreciate!). Example: ₹50L property in Pune (2015) → ₹85L (2025) = 5.5% CAGR. Compare: Nifty 50 = 12% CAGR same period. Real estate LAGS equity in returns but: (1) Less volatile, (2) Tangible, (3) Rental income, (4) Emotional value (own home)." },
    { question: "What is RERA and how does it protect buyers?", answer: "RERA (Real Estate Regulatory Authority) = Protects home buyers. Mandatory for builders: (1) Register all projects, (2) Cannot sell before RERA approval, (3) Deposit 70% customer money in escrow (cannot misuse!), (4) Penalties for delays (builder pays interest!). Buyer: Always check RERA registration before booking. Complaint: File on rera.maharashtra.gov.in (state-wise portal). RERA reduced fraud 70%!" },
    { question: "Should I invest in under-construction or ready property?", answer: "Under-construction: 10-20% cheaper, GST 12%, possession risk (delays common 2-3 years!), RERA protection. Ready: Immediate possession, no GST, higher price, see actual property. Best: Under-construction from reputed builder (Godrej, Tata, Lodha) with RERA + good track record. Avoid: Small builders, delayed projects, promise of 'high appreciation'!" },
    { question: "What is stamp duty and can I save on it?", answer: "Stamp duty = State tax on property registration (5-7% of property value). Maharashtra: 5% (men), 4% (women save 1%!). Karnataka: 5%. Delhi: 6%. Save by: (1) Register in woman's name (1-2% lower in many states), (2) Check exemptions (first-time buyers, affordable housing), (3) Buy in SEZ (some exemptions). Cannot avoid - must pay to get legal ownership!" },
    { question: "What is property tax and annual maintenance?", answer: "Annual costs after buying: (1) Property tax: 0.1-0.3% of guidance value (₹1Cr = ₹10-30K/year), (2) Society maintenance: ₹2-5/sq ft (2000 sq ft = ₹50K-1.2L/year), (3) Repairs: ₹50K-2L/year, (4) Insurance: ₹5-10K/year. Total: ₹1.5-3L/year on ₹1Cr property. Factor this in ROI calculation!" },
    { question: "Can I get loan on REIT units?", answer: "NO! Banks don't give loans against REIT units (like stocks). Can get margin from broker (50% margin = 2x leverage) but risky! For property investment with leverage: Buy physical property (70-80% loan). REITs: Only for cash investment (no leverage)." },
    { question: "What is property flipping and is it profitable?", answer: "Flipping = Buy under-construction, sell before possession. Profit: 20-40% in 2-3 years (if location appreciates). Example: Book ₹80L (under-construction), sell at ₹1.1Cr (on completion) = ₹30L profit. Risk: (1) Project delays, (2) Market crash, (3) Finding buyer, (4) Capital gains tax (30% STCG if sold within 2 years). Works apenas in hot markets - very risky!" },
    { question: "How to do legal due diligence before buying property?", answer: "10-point checklist: (1) Original sale deed, (2) Encumbrance certificate (no legal disputes), (3) Approved building plan, (4) Completion certificate, (5) Occupancy certificate, (6) Property tax receipts, (7) NOC from society, (8) Check seller's chain of ownership (15+ years), (9) Physical survey, (10) Hire lawyer (₹25-50K - worth it!). Skip due diligence = risk buying disputed property!" },
    { question: "REITs vs Real Estate mutual funds: difference?", answer: "REITs: Own actual commercial properties (malls, offices), rental income distributed (5-7% yield), listed on stock exchange, min ₹10K. Real estate MF: Invests in real estate companies' shares (DLF, Prestige, Godrej Properties), returns from stock appreciation, not rental income. REITs = passive rental income. Real estate MF = equity bet on developers. REITs more stable!" },
    { question: "What is carpet area vs built-up area vs super built-up area?", answer: "Carpet area = Actual usable area (wall-to-wall inside flat). Built-up = Carpet + walls + balcony (20-25% more). Super built-up = Built-up + share of common areas (25-35% more). Example: Carpet 800 sq ft → Built-up 1000 sq ft → Super built-up 1100 sq ft. Builder charges per super built-up (highest!). Always ask: Carpet area = actual space you live in." }
  ];

  return (<><SEOHelmet title="Real Estate Investment India 2025: Residential, Commercial, REITs Complete Guide | MoneyCal" description="Complete real estate investment guide: Residential vs commercial property, REITs (₹10K minimum, 5-7% yield), rental yield (2-3% residential, 6-9% commercial), capital appreciation (5-8%), stamp duty (5-7%), property taxes, RERA protection, legal due diligence checklist. Hindi + English" keywords="real estate investment India 2025, REITs India, property investment, rental yield, commercial vs residential, stamp duty, RERA, legal due diligence, रियल एस्टेट निवेश गाइड" url="/learn/advanced-specialised-finance/real-estate-investment-india-residential-commercial-reits-property-guide-2025" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50"><header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 text-gray-600 hover:text-blue-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-gray-600">Lesson 1 of 7</span><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-blue-500 to-indigo-600 rounded-xl shadow-lg"><Home className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-blue-600 uppercase tracking-wide">Lesson 1 • 55 Minutes • Advanced</div><h1 className="text-4xl font-bold text-gray-900">Real Estate Investment 2025</h1><p className="text-xl text-gray-600 mt-1">Residential, Commercial, REITs Guide</p></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ FAQs</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-blue-600 to-indigo-600 rounded-2xl p-8 text-white shadow-2xl text-center"><Award className="w-12 h-12 mx-auto mb-4" /><h3 className="text-3xl font-bold mb-4">🎉 Done!</h3><Link to="/learn/advanced-specialised-finance" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-blue-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Next<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default RealEstateInvestment;