/**
 * Indian finance & business RSS feeds for Money Shorts "Trending from India".
 * Used by client (with 2h cache) and by GitHub Action script to refresh every 2 hours.
 */

export interface TrendingRssItem {
  title: string;
  link: string;
  pubDate: string;
  thumbnail?: string;
  description?: string;
  source: string;
  sourceUrl?: string;
}

export interface TrendingRssFeedResult {
  updatedAt: string; // ISO
  items: TrendingRssItem[];
}

/** Indian finance/business RSS feed URLs (for rss2json: pass encoded URL). */
export const INDIAN_TRENDING_RSS_FEEDS: { url: string; name: string }[] = [
  { url: 'https://www.moneycontrol.com/rss/latestnews.xml', name: 'Moneycontrol' },
  { url: 'https://economictimes.indiatimes.com/rssfeedstopstories.cms', name: 'Economic Times' },
  { url: 'https://www.business-standard.com/rss/home_page_top_stories.rss', name: 'Business Standard' },
  { url: 'https://www.livemint.com/rss/companies', name: 'Livemint' },
  { url: 'https://www.financialexpress.com/feed/', name: 'Financial Express' },
];

export const TRENDING_RSS_CACHE_KEY = 'moneycal_trending_rss';
export const TRENDING_RSS_CACHE_TTL_MS = 2 * 60 * 60 * 1000; // 2 hours

/** Path to static JSON generated by GitHub Action (updated every 2h). */
export const TRENDING_RSS_JSON_PATH = '/trending-rss-feed.json';
