import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, Building, CheckCircle, Award, HelpCircle } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const BusinessRegistrationGuide: React.FC = () => {
  const faqData = [
    { question: "Sole vs LLP vs Pvt Ltd: Complete comparison?", answer: "Sole: ₹0 cost, unlimited liability, owner = business, easiest compliance, suitable for freelancers. LLP: ₹15K cost, limited liability (safe!), 2+ partners, moderate compliance, suitable for professionals. Pvt Ltd: ₹10K cost, limited liability, shareholder ownership, high compliance, investor-friendly, suitable for startups. Tax: Sole/LLP = slab rates (0-30%). Pvt Ltd = 25% flat." },
    { question: "How to register company online?", answer: "On MCA portal (mca.gov.in): (1) Get DSC (Digital Signature) - ₹1,500, (2) Get DIN (Director ID) - free, (3) Reserve name (RUN) - ₹1,000, (4) File SPICe+ form with MOA/AOA - ₹5,000, (5) Get COI (Certificate) in 7 days. Total: ₹10-15K. Or hire CA (₹10-20K professional fees). Takes 10-15 days total!" },
    { question: "What is the minimum investment needed to start Pvt Ltd?", answer: "NO MINIMUM! Can start with apenas ₹1,000 paid-up capital (but ₹1L authorized capital minimum). Example: Authorized ₹1L, Paid-up ₹10K. Two directors with ₹5K each. Practically: Start with ₹1-2L for credibility. Investors prefer higher paid-up (shows commitment)!" },
    { question: "Can I run business without registration?", answer: "Legal for sole proprietorship (no registration needed for business itself). But need: (1) GST (if turnover more than ₹40L), (2) Shop & Establishment license, (3) Trade license (municipality), (4) Professional tax (state-wise), (5) Udyam (MSME - free!). Can start without registration, but register as you grow for credibility + benefits!" },
    { question: "How long does business registration take?", answer: "Sole: 1 day (just open current account). LLP: 7-15 days. Pvt Ltd: 7-15 days. OPC: 10 days. Delays if: Name rejection, incorrect documents, RoC queries. Fast-track: Use professionals (CA/CS), pay ₹5-10K extra for 3-5 day registration. Apply early - don't wait till urgent!" },
    { question: "What happens if I don't comply with MCA filings?", answer: "Penalties: (1) Form AOC-4 (annual accounts) late: ₹100/day, (2) Form MGT-7 (annual return) late: ₹100/day, (3) DIN KYC not filed: DIN deactivated (director disqualified!), (4) Continuous defaults: Company struck off. Comply on time - set calendar reminders in March-April every year!" },
    { question: "Can foreign nationals be directors in Indian company?", answer: "YES! No restriction. But: (1) Need India address for at least one director, (2) DIN from MCA (takes 15 days), (3) OCI/PIO card helpful, (4) Indian director signing authority for MCA filings. Many startups have: Indian + foreign co-founders as directors. Legal and common!" },
    { question: "What is the best structure for startups raising VC funding?", answer: "Private Limited Company ONLY! VCs don't invest in sole/LLP. Why: (1) Clear share structure, (2) Easy equity transfer, (3) Legal entity separate from founders, (4) Can issue ESOP to employees. Don't start as LLP then convert (wastes time + ₹50K). Start as Pvt Ltd if planning to raise funding!" },
    { question: "Do I need a CA to register business?", answer: "Not mandatory but recommended! Sole/LLP: Can do yourself (save ₹10-15K). Pvt Ltd: DIY possible but risky (one mistake = rejection). CA costs: Sole ₹3-5K, LLP ₹10-15K, Pvt Ltd ₹10-20K. They handle: Name reservation, forms, MOA/AOA, compliance. Worth it for Pvt Ltd (complex forms!). Save money on Sole/LLP (simple process)." },
    { question: "What is trademark registration and is it necessary?", answer: "Trademark = Brand name/logo protection. Register on ipindia.gov.in. Cost: ₹5-10K. Time: 12-18 months. Necessary if: (1) Unique brand (not generic like 'Mumbai Bakery'), (2) Planning to scale, (3) E-commerce (Amazon requires for brand registry). Start business first, register trademark when established (6-12 months later). Not urgent initially!" }
  ];

  return (<><SEOHelmet title="Business Registration India 2025: Sole Proprietorship, LLP, Private Limited Complete Guide | MoneyCal" description="Choose right business structure: Sole proprietorship (easiest, unlimited liability, ₹0 cost), LLP (₹15K registration, limited liability, 2+ partners), Pvt Ltd (₹10K+, investor-friendly, limited liability), pros/cons, compliance costs, registration process. Hindi + English" keywords="business registration India 2025, sole proprietorship, LLP registration, private limited company, OPC, business structure comparison, MCA registration, व्यवसाय पंजीकरण गाइड" url="/learn/business-finance-entrepreneurship/business-registration-india-sole-proprietorship-llp-private-limited-company-guide-2025" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-teal-50 via-cyan-50 to-blue-50"><header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 text-gray-600 hover:text-teal-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-gray-600">Lesson 5 of 8</span><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 px-4 py-2 bg-teal-600 text-white rounded-lg hover:bg-teal-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-teal-500 to-cyan-600 rounded-xl shadow-lg"><Building className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-teal-600 uppercase tracking-wide">Lesson 5 • 45 Minutes • Beginner</div><h1 className="text-4xl font-bold text-gray-900">Business Registration 2025</h1><p className="text-xl text-gray-600 mt-1">Sole, LLP, or Pvt Ltd?</p></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ FAQs</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-teal-600 to-cyan-600 rounded-2xl p-8 text-white shadow-2xl text-center"><Award className="w-12 h-12 mx-auto mb-4" /><h3 className="text-3xl font-bold mb-4">🎉 Done!</h3><Link to="/learn/business-finance-entrepreneurship/scaling-business-strategies-india-hiring-automation-expansion-profitability-2025" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-teal-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Next<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default BusinessRegistrationGuide;