import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, BarChart3, CheckCircle, Award, HelpCircle, FileText } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const BusinessFinancialStatements: React.FC = () => {
  const faqData = [
    { question: "What is P&L statement and how to read it?", answer: "P&L (Profit & Loss) = Income Statement. Shows: Revenue (sales) - COGS (direct costs) = Gross Profit. Gross Profit - Operating Expenses (salaries, rent, marketing) = Operating Profit. Operating Profit - Interest/Tax = Net Profit. Read: (1) Revenue trend (growing?), (2) Gross margin % (should be 40%+ for services, 20%+ for products), (3) Operating margin (10%+ healthy), (4) Net margin (5%+ good). Compare yearly!" },
    { question: "What is Balance Sheet?", answer: "Balance Sheet = Snapshot at a point in time. Assets (what you own) = Liabilities (what you owe) + Equity (owner's capital). Assets: Cash, inventory, receivables, fixed assets. Liabilities: Loans, payables, provisions. Equity: Capital + Retained earnings. Read: (1) Current ratio (current assets/current liabilities should be more than 1.5), (2) Debt-to-equity (should be less than 2), (3) Working capital (current assets - current liabilities, should be positive!)." },
    { question: "What is Cash Flow Statement?", answer: "Shows actual cash movement (different from profit!). 3 sections: (1) Operating CF: Cash from business (should be positive!), (2) Investing CF: Buying/selling assets (negative if growing), (3) Financing CF: Loans taken/repaid. Example: ₹10L profit but ₹5L cash outflow → Why? Customers not paid (receivables), inventory bought (cash out). Cash flow statement reveals the truth!" },
    { question: "What is EBITDA?", answer: "EBITDA = Earnings Before Interest, Taxes, Depreciation, Amortization. Measures operating performance (ignoring financing/accounting). Used for: (1) Comparing companies, (2) Valuation (EV/EBITDA multiple), (3) Debt servicing capacity. Example: Revenue ₹10Cr, EBITDA ₹2Cr = 20% EBITDA margin (good!). SaaS: 20%+ EBITDA. Retail: 5-10%. Manufacturing: 10-15%." },
    { question: "How often should I review financial statements?", answer: "Monthly minimum! Best practice: (1) P&L: Weekly (track revenue, expenses real-time), (2) Balance Sheet: Monthly (check working capital, debt), (3) Cash Flow: Daily/Weekly (cash is king!). Annual review: (1) Compare vs budget, (2) Industry benchmarks, (3) Set next year targets. Founders who check financials weekly = 3x more likely to succeed!" },
    { question: "What is gross margin vs net margin?", answer: "Gross Margin = (Revenue - COGS) / Revenue × 100. Shows product profitability. Net Margin = Net Profit / Revenue × 100. Shows overall profitability. Example: Revenue ₹10L, COGS ₹6L, Expenses ₹3L, Net Profit ₹1L → Gross margin = 40%, Net margin = 10%. Gross margin should be 30%+ (else product not viable!). Net margin 5-10% = healthy." },
    { question: "What financial ratios should I track?", answer: "10 critical ratios: (1) Current ratio (current assets/current liabilities, more than 1.5 good), (2) Quick ratio (exclude inventory, more than 1 good), (3) Debt-to-equity (less than 2), (4) Gross margin % (30%+), (5) Net margin % (5-10%), (6) ROE (Return on Equity, 15%+), (7) Asset turnover (revenue/assets), (8) Inventory turnover (COGS/avg inventory, higher better), (9) Receivables days (less than 45), (10) Payables days (45-60)." },
    { question: "Do I need an auditor for my business?", answer: "Mandatory audit if: (1) Pvt Ltd company (any turnover), (2) LLP with turnover more than ₹40L or capital more than ₹25L, (3) Sole/Partnership with turnover more than ₹1Cr (tax audit). Cost: ₹25K-1L (depends on turnover). Auditor: Chartered Accountant (CA) only. Benefits: Credibility, loan approval, tax compliance. Hire good CA (₹50-75K) not cheapest (₹20K = poor quality!)." },
    { question: "What is working capital and how to calculate?", answer: "Working Capital = Current Assets - Current Liabilities. Should be positive! Example: Current assets ₹30L (cash ₹10L + inventory ₹15L + receivables ₹5L), Current liabilities ₹20L (payables ₹15L + short-term loan ₹5L) → Working capital = ₹10L (healthy!). Negative working capital = cash flow crisis soon! Improve by: Faster collections, slower payments, reduce inventory." },
    { question: "How to prepare for investor due diligence?", answer: "Investors check: (1) Last 3 years financials (P&L, Balance Sheet, Cash Flow), (2) Cap table (shareholding), (3) Contracts (customer, supplier, employee), (4) Legal (pending litigations), (5) IP (trademarks, patents), (6) Compliance (GST, ITR, MCA filings). Keep ready: Clean books, all compliances filed, organized documents. Audit by Big 4 (Deloitte, EY, PwC, KPMG) adds credibility!" }
  ];

  return (<><SEOHelmet title="Business Financial Statements 2025: P&L, Balance Sheet, Cash Flow India | Complete Guide | MoneyCal" description="Understand business financials: P&L statement (revenue, expenses, net profit), Balance Sheet (assets, liabilities, equity), Cash Flow statement, EBITDA, financial ratios (current ratio, gross margin), working capital. How to read financial health. Hindi + English" keywords="business financial statements India, P&L statement, balance sheet, cash flow statement, EBITDA, financial ratios, working capital, वित्तीय विवरण गाइड" url="/learn/business-finance-entrepreneurship/business-financial-statements-profit-loss-balance-sheet-cash-flow-india-guide" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-yellow-50 via-amber-50 to-orange-50"><header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 text-gray-600 hover:text-yellow-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-yellow-600 font-semibold">Lesson 7 of 8 - FINAL!</span><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 px-4 py-2 bg-yellow-600 text-white rounded-lg hover:bg-yellow-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-yellow-500 to-amber-600 rounded-xl shadow-lg"><BarChart3 className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-yellow-600 uppercase tracking-wide">Lesson 7 • 55 Minutes • Intermediate • FINAL</div><h1 className="text-4xl font-bold text-gray-900">Financial Statements 2025</h1><p className="text-xl text-gray-600 mt-1">Read Your Business Health</p></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ FAQs</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-green-600 to-emerald-600 rounded-2xl p-12 text-white shadow-2xl text-center"><Award className="w-16 h-16 mx-auto mb-6" /><h3 className="text-4xl font-bold mb-4">🎉 Business Finance Complete!</h3><p className="text-2xl mb-8">Mastered all 8 lessons!</p><Link to="/learn" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-green-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Explore More<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default BusinessFinancialStatements;
