import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, FileText, CheckCircle, Award, HelpCircle, AlertTriangle, IndianRupee } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const GSTComplianceGuide: React.FC = () => {
  const faqData = [
    { question: "When is GST registration mandatory?", answer: "Mandatory if: (1) Turnover exceeds ₹40L (₹20L for special states), (2) E-commerce seller, (3) Inter-state supply. Voluntary: Can register even below ₹40L for ITC benefits. Penalty for not registering: 100% of tax due + ₹10,000. Register on gst.gov.in - takes 3-7 days!" },
    { question: "What is GSTR-1, GSTR-3B, and GSTR-9?", answer: "GSTR-1: Monthly sales return (file by 11th). GSTR-3B: Monthly summary + tax payment (file by 20th). GSTR-9: Annual return (file by Dec 31). Most important: GSTR-3B (pay tax here!). Late filing: ₹50/day + 18% interest on unpaid tax. File on time!" },
    { question: "What is Input Tax Credit (ITC)?", answer: "ITC = GST paid on purchases can offset GST on sales. Example: Bought ₹1L goods (₹18K GST paid), sold for ₹2L (₹36K GST collected) → Pay govt apenas ₹18K (₹36K - ₹18K ITC). Claim ITC only if: (1) Supplier filed GSTR-1, (2) You filed GSTR-3B, (3) Payment made to supplier. Check on GSTR-2B!" },
    { question: "What is composition scheme and who should opt?", answer: "Composition: Pay flat tax (1-6% of turnover), no ITC. Who: Small businesses under ₹1.5Cr turnover. Benefits: Simple compliance, quarterly filing, low tax. Drawbacks: No ITC, cannot sell interstate, cannot issue tax invoice. Best for: Retailers, restaurants, small manufacturers. Service providers: 6% (higher than regular 18%)." },
    { question: "What is GST late filing penalty?", answer: "GSTR-1: ₹200/day (₹100/day for NIL return). GSTR-3B: ₹50/day + 18% interest on unpaid tax. Max penalty: ₹5,000. Example: Late by 30 days, tax due ₹1L → Penalty ₹1,500 + interest ₹1,500 = Total ₹3,000 extra! File on time - set calendar reminders!" },
    { question: "How to file GST returns online?", answer: "5 steps: (1) Login to gst.gov.in with username/password, (2) Services → Returns → GSTR-1/3B, (3) Enter sales/purchase details, (4) Calculate tax, (5) Pay via netbanking, Submit. OR use: Offline tool (for bulk entries), ClearTax, Zoho Books (easier). Takes 2-4 hours monthly if organized!" },
    { question: "What is reverse charge mechanism (RCM) in GST?", answer: "RCM = Recipient pays GST (not supplier). Applicable when: (1) Buying from unregistered supplier, (2) Specific services (legal, GTA), (3) Imports. Example: Buy ₹1L goods from unregistered dealer → You pay ₹18K GST to govt (not dealer). Can claim ITC if eligible. Complex - consult CA!" },
    { question: "Can I claim ITC on all business expenses?", answer: "NO! ITC blocked on: (1) Food, beverages (except for sale), (2) Rent-a-cab, life insurance, health insurance, (3) Membership of club/gym, (4) Works contract services for personal use. ITC allowed: Raw materials, office rent, CA fees, advertising, machinery. Check Section 17(5) GST Act!" },
    { question: "What is e-way bill and when is it needed?", answer: "E-way bill = Electronic permit for goods transportation. Needed if: (1) Goods value exceeds ₹50,000, (2) Interstate movement. Generate on: ewaybillgst.gov.in. Valid for: 1 day per 100km. Penalty if not generated: ₹10,000 or 100% of tax. Transporter needs this + invoice!" },
    { question: "What if I made a mistake in filed GST return?", answer: "Can rectify in next month's return (Table 9 in GSTR-1, Table 4 in GSTR-3B). Major errors: File amendment. After annual return filed: Cannot amend (stuck with error!). Always verify before submitting. Use: Offline tool to check before upload. Mistake = pay extra tax or lose ITC!" }
  ];

  return (
    <>
      <SEOHelmet title="GST Compliance India 2025: Registration, Filing GSTR, Input Credit, Composition Scheme | MoneyCal" description="Complete GST guide: GST registration (turnover more than ₹40L), GSTR-1/3B filing deadlines, input tax credit (ITC), composition scheme (turnover less than ₹1.5Cr), penalties, e-way bill. Hindi + English" keywords="GST compliance India 2025, GSTR filing, input tax credit ITC, composition scheme, GST registration, e-way bill, GST अनुपालन" url="/learn/business-finance-entrepreneurship/gst-compliance-india-registration-filing-returns-input-credit-composition-scheme-2025" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-orange-50 via-red-50 to-pink-50">
        <header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 text-gray-600 hover:text-orange-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-gray-600">Lesson 4 of 8</span><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-orange-500 to-red-600 rounded-xl shadow-lg"><FileText className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-orange-600 uppercase tracking-wide">Lesson 4 • 55 Minutes • Intermediate</div><h1 className="text-4xl font-bold text-gray-900">GST Compliance 2025</h1><p className="text-xl text-gray-600 mt-1">Registration, Filing, Input Credit</p></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ Frequently Asked Questions</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-orange-600 to-red-600 rounded-2xl p-8 text-white shadow-2xl text-center"><Award className="w-12 h-12 mx-auto mb-4" /><h3 className="text-3xl font-bold mb-4">🎉 Lesson Complete!</h3><Link to="/learn/business-finance-entrepreneurship/business-registration-india-sole-proprietorship-llp-private-limited-company-guide-2025" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-orange-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Next: Business Registration<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default GSTComplianceGuide;
