# MoneyCal - Automatic Content Extractor from Sitemap
# Reads sitemap.xml and builds content database automatically

Write-Host "`n=========================================" -ForegroundColor Cyan
Write-Host "  AUTO CONTENT EXTRACTOR" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

# Load sitemap.xml
$sitemapPath = "..\public\sitemap.xml"
Write-Host "`nLoading sitemap from: $sitemapPath" -ForegroundColor Yellow

if (-not (Test-Path $sitemapPath)) {
    Write-Host "ERROR: Sitemap not found!" -ForegroundColor Red
    exit
}

[xml]$sitemap = Get-Content $sitemapPath -Encoding UTF8

# Extract all URLs with priority 1.0 and 0.9 (latest and most important)
$urls = $sitemap.urlset.url | Where-Object { 
    [double]$_.priority -ge 0.9 -and $_.loc -notlike "*#*"
} | Select-Object -First 100

Write-Host "Found $($urls.Count) high-priority URLs" -ForegroundColor Green

# Categorize URLs automatically
function Get-Category($url) {
    switch -Wildcard ($url) {
        "*festival-tools*" { return "Festival Tool" }
        "*religious-tools*" { return "Religious Tool" }
        "*calculators/sip*" { return "SIP Calculator" }
        "*calculators/emi*" { return "EMI Calculator" }
        "*calculators/tax*" { return "Tax Calculator" }
        "*calculators/loan*" { return "Loan Calculator" }
        "*calculators/insurance*" { return "Insurance Calculator" }
        "*calculators/ppf*" { return "PPF Calculator" }
        "*calculators/fd*" { return "FD Calculator" }
        "*calculators/nps*" { return "NPS Calculator" }
        "*calculators/gst*" { return "GST Calculator" }
        "*finance-tools*" { return "Finance Tool" }
        "*tax-tools*" { return "Tax Tool" }
        "*government-schemes*" { return "Government Scheme" }
        "*crypto*" { return "Crypto Finance" }
        "*astro-finance*" { return "Astro Finance" }
        "*blog*" { return "Financial Blog" }
        "*festival-dates*" { return "Festival Calendar" }
        default { return "Financial Tool" }
    }
}

# Generate title from URL
function Get-Title($url) {
    $path = $url -replace 'https://moneycal.in/', ''
    $title = $path -replace '/', ' ' -replace '-', ' '
    $title = (Get-Culture).TextInfo.ToTitleCase($title.ToLower())
    return $title + " | MoneyCal"
}

# Build content database
$contentItems = @()
$today = Get-Date -Format "yyyy-MM-dd"

foreach ($url in $urls) {
    $loc = $url.loc
    $lastmod = $url.lastmod
    $priority = [double]$url.priority
    
    # Skip homepage and category pages
    if ($loc -eq "https://moneycal.in/" -or $loc -match '/$') {
        continue
    }
    
    $item = [PSCustomObject]@{
        title = Get-Title $loc
        url = $loc
        description = "Explore this valuable resource from MoneyCal! Click to access our comprehensive tool and start making smarter financial decisions today."
        category = Get-Category $loc
        priority = if ($priority -ge 1.0) { "high" } else { "medium" }
        dateAdded = $lastmod
        isNew = ($lastmod -eq $today)
    }
    
    $contentItems += $item
}

Write-Host "Extracted $($contentItems.Count) content items" -ForegroundColor Green

# Sort by date (newest first) and priority
$contentItems = $contentItems | Sort-Object @{Expression={$_.isNew}; Descending=$true}, @{Expression={$_.dateAdded}; Descending=$true}, priority -Descending

# Save to JSON
$output = @{
    lastUpdated = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    totalItems = $contentItems.Count
    autoGenerated = $true
    items = $contentItems
}

$outputPath = Join-Path $PSScriptRoot "content-database-AUTO.json"
$output | ConvertTo-Json -Depth 10 | Set-Content $outputPath -Encoding UTF8

Write-Host "`nContent database saved to: content-database-AUTO.json" -ForegroundColor Green
Write-Host "Total items: $($contentItems.Count)" -ForegroundColor Cyan
Write-Host "New items today: $($contentItems | Where-Object {$_.isNew} | Measure-Object | Select-Object -ExpandProperty Count)" -ForegroundColor Yellow

Write-Host "`n=========================================" -ForegroundColor Cyan
Write-Host "  EXTRACTION COMPLETE!" -ForegroundColor Cyan
Write-Host "=========================================`n" -ForegroundColor Cyan




