import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, TrendingUp, CheckCircle, Award, HelpCircle, Users } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const ScalingBusinessStrategies: React.FC = () => {
  const faqData = [
    { question: "When should I scale my business?", answer: "Scale when: (1) Product-market fit proven (customers love product, retention more than 40%), (2) Positive unit economics (LTV/CAC more than 3), (3) Repeatable sales process, (4) Enough funding (₹1-5Cr+ for scaling), (5) Can't serve all demand (have to turn away customers). DON'T scale if: Losing money on each sale, product not ready, no clear process. Fix product first, then scale!" },
    { question: "How to hire right people for scaling?", answer: "5-step hiring: (1) Define role clearly (JD with KPIs), (2) Source: LinkedIn, Naukri, referrals (best!), (3) Interview: 2-3 rounds (skill + culture fit), (4) Background check, (5) Probation 3-6 months. Pay: Market rate (not 20% below - get average talent!). First 10 hires critical - A players attract more A players. Hire slow, fire fast!" },
    { question: "What business processes to automate first?", answer: "Automate in order: (1) Accounting (Zoho Books, Tally), (2) Invoicing (automated email + reminders), (3) Inventory management, (4) Customer support (chatbot for FAQ), (5) Marketing (email automation, social media scheduling), (6) HR/payroll (Razorpay Payroll, Keka). ROI: Automation costs ₹5-20K/month, saves 100-200 hours. Automate repetitive tasks first!" },
    { question: "How to maintain profitability while scaling?", answer: "7 strategies: (1) Monitor unit economics weekly (CAC, LTV, margins), (2) Don't grow revenue at expense of margins (₹10Cr revenue, 2% margin worse than ₹2Cr revenue, 20% margin!), (3) Increase prices (most companies underprice!), (4) Cut bottom 20% unprofitable customers/products, (5) Negotiate better supplier terms (volume discount), (6) Automate to reduce labor costs, (7) Hire for leverage (1 manager can supervise 10 people)." },
    { question: "Should I expand to new cities or go deep in existing city?", answer: "Go DEEP first! Dominate one city before expanding. Why: (1) Lower delivery cost (concentrated area), (2) Word-of-mouth in local community, (3) Can test & fix issues quickly, (4) Better customer service. Expand to city 2 when: (1) 30%+ market share in city 1, (2) Strong brand recall, (3) Profitable in city 1, (4) Processes replicate easily. Premature expansion = capital burn!" },
    { question: "What is the biggest mistake when scaling?", answer: "Scaling TOO FAST without foundation! Blitzscaling works apenas for funded startups in winner-takes-all markets. For most: (1) Grow 50-100%/year (not 10x overnight!), (2) Hire when revenue supports (not before), (3) Expand to city 2 only when city 1 profitable, (4) Build processes before scaling (chaos otherwise). Slow & steady wins - 99% of businesses aren't Flipkart/Zomato!" },
    { question: "How much should I invest in marketing while scaling?", answer: "Rule: 10-20% of revenue in marketing. Example: ₹1Cr revenue → ₹10-20L marketing budget. Track CAC (Customer Acquisition Cost): Total marketing ÷ New customers. CAC should be less than LTV/3. If CAC more than LTV = stop marketing, fix product! Channels: Digital ads (measurable), referrals (cheapest), content marketing (long-term)." },
    { question: "Should I raise funding to scale or bootstrap?", answer: "Raise funding if: (1) Winner-takes-all market (need to grow fast before competitor), (2) High initial investment (manufacturing, tech), (3) Long payback period (SaaS). Bootstrap if: (1) Service business (low capex), (2) Profitable from day 1, (3) Want full control. Hybrid: Bootstrap to ₹1Cr, then raise for scaling. Don't: Raise too early (expensive equity) or too late (lose market!)." },
    { question: "How to scale without losing company culture?", answer: "8 tactics: (1) Hire for culture fit (skills can be taught!), (2) Document values early (what you stand for), (3) Onboarding process (culture immersion for new hires), (4) Regular team meetings (weekly all-hands), (5) Celebrate wins publicly, (6) Fire toxic high-performers (they poison culture), (7) Founders model behavior (culture flows from top), (8) Keep rituals alive (Friday team lunch, monthly outings)." },
    { question: "What KPIs to track when scaling?", answer: "10 critical KPIs: (1) Revenue growth (MoM/YoY), (2) Gross margin % (revenue - COGS), (3) Net profit margin %, (4) CAC (Customer Acquisition Cost), (5) LTV (Customer Lifetime Value), (6) LTV/CAC ratio (should be more than 3), (7) Burn rate (monthly cash out), (8) Cash runway (months left), (9) Employee productivity (revenue per employee), (10) Customer retention % (should be 40%+). Track weekly!" }
  ];

  return (<><SEOHelmet title="Scaling Business Strategies 2025: Hiring, Automation, Expansion, Profitability India | MoneyCal" description="Scale your business: When to scale (product-market fit, unit economics), hiring strategies, automation tools (Zoho, Tally), geographical expansion, maintaining profitability while scaling, KPIs to track. Hindi + English" keywords="scaling business strategies India 2025, hiring, business automation, geographical expansion, unit economics, profitability, KPIs, व्यवसाय स्केलिंग रणनीतियां" url="/learn/business-finance-entrepreneurship/scaling-business-strategies-india-hiring-automation-expansion-profitability-2025" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50"><header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 text-gray-600 hover:text-indigo-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-gray-600">Lesson 6 of 8</span><Link to="/learn/business-finance-entrepreneurship" className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-xl shadow-lg"><TrendingUp className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-indigo-600 uppercase tracking-wide">Lesson 6 • 50 Minutes • Advanced</div><h1 className="text-4xl font-bold text-gray-900">Scaling Strategies 2025</h1><p className="text-xl text-gray-600 mt-1">From ₹1Cr to ₹100Cr Revenue</p></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ FAQs</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl p-8 text-white shadow-2xl text-center"><Award className="w-12 h-12 mx-auto mb-4" /><h3 className="text-3xl font-bold mb-4">🎉 Done!</h3><Link to="/learn/business-finance-entrepreneurship/business-financial-statements-profit-loss-balance-sheet-cash-flow-india-guide" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-indigo-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Next<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default ScalingBusinessStrategies;