import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, TrendingUp, CheckCircle, Award, HelpCircle, AlertTriangle, Zap } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const CryptocurrencyGuide: React.FC = () => {
  const faqData = [
    { question: "Should I invest in cryptocurrency?", answer: "Only if: (1) Age under 40, (2) High risk appetite, (3) Can afford 100% loss, (4) Have emergency fund + diversified portfolio, (5) Understand technology. Allocation: Max 1-5% of portfolio. NOT for: Retirement, emergency fund, child education. Crypto = speculation (not investment). 50% crashes common. Indians lost ₹100s crores in scams. Invest apenas play money!" },
    { question: "What is 30% crypto tax in India?", answer: "Budget 2022: 30% flat tax on crypto gains + 1% TDS on every sale (VDA rules). Example: Bought Bitcoin ₹5L, sold ₹8L → ₹3L profit → Tax ₹90,000 (30%). Loss in Bitcoin CANNOT offset gain in Ethereum! No benefit of long-term holding. No deductions allowed. Tax inefficient! Report in ITR under VDA. Penalty for not reporting: 50% of tax + jail!" },
    { question: "How to buy cryptocurrency in India 2025?", answer: "4 steps: (1) Download WazirX/CoinDCX/CoinSwitch app, (2) Complete KYC (Aadhaar, PAN), (3) Add money via UPI (instant), (4) Buy Bitcoin/Ethereum. Min: ₹100. Store: Exchange wallet (easy) or hardware wallet (safer for ₹1L+). Start small (₹5-10K), learn volatility, then invest more if comfortable. Don't invest borrowed money!" },
    { question: "Bitcoin vs Ethereum: which to buy?", answer: "Bitcoin: Digital gold, store of value, limited supply (21M), price ₹35L+ (Nov 2025), less volatile. Ethereum: Smart contract platform, unlimited supply, price ₹2.5L+, more volatile. Beginners: 70% Bitcoin + 30% Ethereum (Bitcoin is 'safer'). Advanced: Add altcoins (Solana, Cardano) for higher risk-return. Never: Put 100% in one coin (diversify!)." },
    { question: "Where to store cryptocurrency safely?", answer: "3 options: (1) Exchange wallet (WazirX): Easy but risky (WazirX hack ₹2,000Cr in 2024!), (2) Software wallet (Trust Wallet, MetaMask): You control private key (safer), (3) Hardware wallet (Ledger, Trezor): ₹5-10K but most secure. For below ₹50K: Exchange OK. Above ₹1L: Hardware wallet must! Never share: Private key, seed phrase (12-24 words)." },
    { question: "Can I earn passive income from crypto staking?", answer: "Yes but risky! Staking: Lock coins, earn 5-15% APY. Example: Stake 1 Ethereum (₹2.5L) at 10% = ₹25K/year. Risk: (1) ETH price can fall 50% (lose ₹1.25L!), (2) Lock-in period (cannot sell), (3) Platform risk (exchange can shut). Better for retail: Bank FD 7% (safe) than crypto staking 10% (can lose principal!). Staking for: Long-term HODLers apenas!" },
    { question: "What happened to crypto in India 2024-25?", answer: "Mixed year! (1) Govt didn't ban (positive), (2) 30% tax + 1% TDS = trading volume down 70%, (3) WazirX hack ₹2,000Cr (July 2024) = users lost money, (4) Bitcoin hit $100K globally (Nov 2024 - all-time high!), (5) Many Indians moved to Binance (foreign exchange - risky!). India: Regulate but cautious. Legal to trade but heavily taxed!" },
    { question: "Is crypto legal in India 2025?", answer: "YES! Legal to buy/sell/hold BUT not legal tender (shops not required to accept). Can trade on: WazirX, CoinDCX, CoinSwitch (Indian exchanges). BUT: (1) 30% tax on gains, (2) 1% TDS on sales, (3) Not regulated by RBI/SEBI (no investor protection), (4) Govt can change rules anytime. Legal status: Allowed but discouraged (via heavy taxation)!" },
    { question: "What are crypto scams in India?", answer: "5 common scams: (1) Ponzi schemes (OneCoin - promise 10%/month!), (2) Fake exchanges (website looks real, steals money), (3) WhatsApp pump-dump (buy XYZ coin, scammer dumps on you), (4) Giveaway scams (send 1 BTC, get 2!), (5) Phishing (fake WazirX email). Use ONLY: WazirX, CoinDCX, CoinSwitch. Verify website URL! If offer too good = SCAM!" },
    { question: "Can I use crypto for payments in India?", answer: "Practically NO! (1) 99% shops don't accept (not legal tender), (2) High fees ($5-20 per transaction), (3) Slow (Bitcoin 10 min, Ethereum 1 min), (4) Price volatility (your ₹100 coffee becomes ₹120 by payment time!). UPI is 1000x better (instant, zero cost). Crypto = investment asset (like gold), NOT payment method!" },
    { question: "How to report cryptocurrency in ITR?", answer: "Mandatory! Schedule VDA in ITR-2: Show all crypto sales (coin, buy price, sell price, date). Total gains taxed at 30%. Losses cannot offset. Also: 1% TDS shown in Form 26AS. File by July 31. Penalty if not reported: 50% of tax + interest + prosecution! Even ₹100 gain = report. IT department tracks via exchange data!" }
  ];

  return (<><SEOHelmet title="Cryptocurrency Investment 2025: Bitcoin, Ethereum, 30% Tax, Regulations India Complete Guide | MoneyCal" description="Invest in crypto in India: Bitcoin, Ethereum, crypto exchanges (WazirX, CoinDCX), 30% flat tax + 1% TDS on transactions, legal status, wallet security (hardware wallet for ₹1L+), staking risks. WARNING: 50% crashes common! Hindi + English" keywords="cryptocurrency investment India 2025, Bitcoin Ethereum, crypto tax 30%, 1% TDS, WazirX CoinDCX, crypto staking, hardware wallet, VDA rules, क्रिप्टोकरेंसी निवेश गाइड" url="/learn/advanced-specialised-finance/cryptocurrency-investment-bitcoin-ethereum-tax-30-percent-tds-regulations-india-2025" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-orange-50 via-yellow-50 to-amber-50"><header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 text-gray-600 hover:text-orange-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-gray-600">Lesson 5 of 7</span><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-orange-500 to-yellow-600 rounded-xl shadow-lg"><Zap className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-orange-600 uppercase tracking-wide">Lesson 5 • 50 Minutes • Advanced</div><h1 className="text-4xl font-bold text-gray-900">Cryptocurrency Investment 2025</h1><p className="text-xl text-gray-600 mt-1">Bitcoin, Ethereum, 30% Tax, Regulations</p></div></div><div className="bg-red-100 border-l-4 border-red-500 p-6 rounded-r-xl"><div className="flex items-start gap-3"><AlertTriangle className="w-6 h-6 text-red-600 flex-shrink-0 mt-1" /><div><strong className="text-red-900">EXTREME RISK WARNING!</strong><p className="text-red-900 mt-2">Crypto can lose 50-90% value overnight. Only invest 1-5% of portfolio. Not for retirement or emergency funds!</p></div></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ FAQs</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-orange-600 to-yellow-600 rounded-2xl p-8 text-white shadow-2xl text-center"><Award className="w-12 h-12 mx-auto mb-4" /><h3 className="text-3xl font-bold mb-4">🎉 Done!</h3><Link to="/learn/advanced-specialised-finance" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-orange-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Next<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default CryptocurrencyGuide;