import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, TrendingUp, CheckCircle, Award, HelpCircle, AlertTriangle } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const DerivativesTrading: React.FC = () => {
  const faqData = [
    { question: "What are derivatives (F&O)?", answer: "Derivatives = Financial instruments deriving value from underlying asset (Nifty, Bank Nifty, stocks). Two types: (1) Futures: Obligation to buy/sell at future date, (2) Options: Right (not obligation) to buy/sell. Use: Speculation (profit from price moves), Hedging (protect portfolio). Extremely risky - 90% of F&O traders lose money! Not for beginners!" },
    { question: "Call vs Put option: difference?", answer: "Call = Right to BUY. Buy call if you think price will rise. Put = Right to SELL. Buy put if you think price will fall. Example: Nifty at 19,000. Buy 19,500 Call at ₹50 premium. If Nifty hits 20,000 → Call worth ₹500 (10x profit!). If stays below 19,500 → Lose entire ₹50 premium. Options = limited loss, unlimited profit (but low probability!)." },
    { question: "What is Nifty and Bank Nifty futures?", answer: "Nifty futures = Bet on Nifty 50 index direction. Lot size: 50 (₹9.5L at 19,000). Margin: 10-15% (₹1-1.5L). Bank Nifty: Banking stocks index. Lot size: 15 (₹6.75L at 45,000). Margin: 15-20% (₹1-1.35L). More volatile than Nifty! Use: Hedge portfolio or speculate. High risk - can lose entire margin in one day!" },
    { question: "What is options premium?", answer: "Premium = Price you pay to buy option. Example: Buy Nifty 19,500 Call at ₹100 premium. Lot size 50 → Total cost ₹5,000 (₹100 × 50). This is maximum loss. If Nifty goes to 20,000 → Option worth ₹500 → Profit ₹400 per share = ₹20,000 total (4x return on ₹5K!). Premium depends on: Strike price, expiry date, volatility." },
    { question: "What are option Greeks (delta, gamma, theta)?", answer: "Delta: How much option price changes per ₹1 change in stock. Delta 0.5 = If stock rises ₹10, option rises ₹5. Gamma: Rate of delta change. Theta: Time decay (option loses value daily as expiry nears). Vega: Volatility impact. Advanced traders track Greeks. Beginners: Just know theta = enemy (value reduces every day!). Options lose value even if stock stays flat!" },
    { question: "Can I lose more than I invest in F&O?", answer: "Futures: YES! Unlimited loss possible. Example: Sell Nifty futures at 19,000 (₹9.5L), it rises to 21,000 → Loss ₹1L (on ₹1.4L margin). Broker will demand more margin or square off. Options: NO! If you BUY options, max loss = premium paid. If you SELL options: Unlimited loss (extremely risky!). Beginners: ONLY buy options, never sell!" },
    { question: "What is hedging using derivatives?", answer: "Hedging = Protect portfolio from downside. Example: Have ₹50L in stocks, fear 10% crash. Buy Nifty Put options worth ₹5L at current level. If market falls 10% → Stock portfolio loses ₹5L BUT Put option gains ₹5L. Net loss = apenas premium paid (₹25K). Insurance for portfolio! Costs 0.5-1% annually." },
    { question: "What is F&O expiry?", answer: "F&O contracts expire last Thursday of every month. On expiry: (1) Futures: Must settle (cash settlement, no delivery), (2) Options: If out-of-money = expire worthless. If in-the-money = auto-exercise or square off. Most traders square off before expiry (avoid physical settlement complications). Expiry week = high volatility!" },
    { question: "Can I trade F&O with small capital?", answer: "Technically yes (₹50K minimum for some options), but: (1) One wrong trade = lose 50-100%, (2) No room for mistakes, (3) Margin calls (broker squares off if insufficient margin). Recommended minimum: ₹5L (for risk management, can take 2-3 losses). Best: Learn for 1 year with paper trading, then start with ₹2-3L. 90% lose money in F&O!" },
    { question: "What is options selling (writing)?", answer: "Selling options = Collect premium upfront. Example: Sell Nifty 19,500 Call, collect ₹100 premium (₹5,000 total). If Nifty stays below 19,500 = keep full premium (₹5K profit!). If Nifty crosses 19,500 = unlimited loss! Risk-reward: Limited profit (premium), unlimited loss. Only for: Experienced traders with ₹10L+ capital + strong risk management. Beginners = never sell options!" },
    { question: "Should beginners trade F&O?", answer: "NO! F&O is NOT investing, it's SPECULATION. Stats: 90% of F&O traders lose money. 5% break even. apenas 5% profit consistently. Beginners: (1) Learn equity investing first (buy stocks, hold 5+ years), (2) Build ₹5-10L portfolio, (3) Then learn F&O theory (6-12 months), (4) Paper trade 6 months, (5) Start with ₹50K (play money). Don't: Jump to F&O directly = 99% lose savings!" }
  ];

  return (<><SEOHelmet title="Derivatives Trading 2025: Futures & Options (F&O), Nifty, Bank Nifty India Complete Guide | MoneyCal" description="Master F&O trading in India: Call & put options explained, Nifty/Bank Nifty futures, margin requirements, option Greeks (delta, gamma, theta), hedging portfolio risk, options strategies. WARNING: 90% traders lose money! Hindi + English" keywords="derivatives trading India 2025, F&O futures options, Nifty options, Bank Nifty, call put options, option Greeks, hedging, margin trading, डेरिवेटिव ट्रेडिंग गाइड" url="/learn/advanced-specialised-finance/derivatives-trading-futures-options-fo-nifty-bank-nifty-hedging-india-2025" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-red-50 via-pink-50 to-rose-50"><header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 text-gray-600 hover:text-red-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-gray-600">Lesson 4 of 7</span><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-red-500 to-pink-600 rounded-xl shadow-lg"><TrendingUp className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-red-600 uppercase tracking-wide">Lesson 4 • 60 Minutes • Advanced</div><h1 className="text-4xl font-bold text-gray-900">Derivatives Trading 2025</h1><p className="text-xl text-gray-600 mt-1">F&O, Options, Nifty - HIGH RISK!</p></div></div><div className="bg-red-100 border-l-4 border-red-500 p-6 rounded-r-xl"><div className="flex items-start gap-3"><AlertTriangle className="w-6 h-6 text-red-600 flex-shrink-0 mt-1" /><div><strong className="text-red-900">WARNING: 90% of F&O traders lose money!</strong><p className="text-red-900 mt-2">Derivatives are extremely risky. Only trade if you have ₹10L+ capital, 2+ years equity experience, and can afford 100% loss!</p></div></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ FAQs</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-red-600 to-pink-600 rounded-2xl p-8 text-white shadow-2xl text-center"><Award className="w-12 h-12 mx-auto mb-4" /><h3 className="text-3xl font-bold mb-4">🎉 Done!</h3><Link to="/learn/advanced-specialised-finance" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-red-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Next<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default DerivativesTrading;
