import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { ArrowRight, ArrowLeft, Globe, CheckCircle, Award, HelpCircle } from 'lucide-react';
import SEOHelmet from '../../../components/SEOHelmet';

const GlobalInvesting: React.FC = () => {
  const faqData = [
    { question: "How to invest in US stocks from India?", answer: "3 ways: (1) Vested/Groww US: Open account, complete KYC, transfer $ via LRS, buy Tesla/Apple. Min: $1 (₹80). (2) International mutual funds: Invest in Indian MFs that buy US stocks (ICICI US Bluechip, Motilal Nasdaq 100). Min: ₹5,000. (3) Direct US broker (Interactive Brokers): Complex, for advanced. Best for beginners: International MFs (rupee investment, no forex hassle!)." },
    { question: "What is LRS limit?", answer: "LRS (Liberalized Remittance Scheme) = RBI allows sending $250,000/year abroad (₹2 Crore). Use for: US stocks, foreign education, gifts, property abroad. Tax: 0.5% TCS (Tax Collected at Source) on amount above ₹7L. Report in ITR! Limit: Per person per financial year. Family of 4 = $1 million (₹8Cr) total limit!" },
    { question: "Should I invest in US stocks or Indian stocks?", answer: "Both! Diversification = strength. US: (1) Access to Apple, Google, Tesla (not in India), (2) Dollar appreciation (₹70 → ₹85 in 10 years = 21% extra!), (3) Stable economy. India: (1) Higher growth (7% GDP vs US 2%), (2) No currency risk, (3) Know market better. Allocation: 70-80% India + 20-30% US (global diversification)!" },
    { question: "What is currency risk in global investing?", answer: "Currency risk = USD/INR fluctuation affects returns. Example: Bought Apple at $150 when ₹/$80 = ₹12,000. Sold at $180 (20% gain) but ₹/$75 = ₹13,500. Actual gain apenas 12.5%! Currency ate 7.5% returns. Works reverse too: If rupee weakens (₹85), same $180 = ₹15,300 (27% gain!). Can't control currency - diversification benefit!" },
    { question: "What are best international mutual funds?", answer: "Top 5: (1) Motilal Oswal Nasdaq 100 FOF (Apple, Google, Microsoft), (2) ICICI US Bluechip (S&P 500), (3) Edelweiss US Technology (tech stocks), (4) PPFAS Flexicap (20-30% international), (5) Nippon India US Equity. Returns: 12-15% (10Y CAGR). Invest via: Groww, Kuvera (SIP ₹1,000/month). Tax: Debt fund taxation (slab rates)!" },
    { question: "Is global investing taxable in India?", answer: "YES! International MFs = Debt fund taxation (no LTCG benefit!). (1) Held more than 3 years: As per slab (30% for high earners), (2) Held less than 3 years: As per slab. Plus: TDS on dividends from US stocks (30% in US, claim foreign tax credit in India). Complex - consult CA! Tax inefficient vs Indian equity (apenas 12.5% LTCG)." },
    { question: "Can I withdraw money from Vested/Groww US?", answer: "YES! Sell stocks → Money in USD wallet → Withdraw to Indian bank (auto-converts to ₹). Charges: $5-7 per withdrawal. Time: 3-5 days. Within LRS limit: No issue. Track: All remittances reported to RBI automatically. Show in ITR under foreign assets!" },
    { question: "Do I need to declare foreign investments in ITR?", answer: "YES! Mandatory if you have: (1) Foreign equity/MF worth more than ₹20L, (2) Any foreign income. Declare in: Schedule FA (Foreign Assets). Penalty for not declaring: ₹10L + 10 years jail (max)! Even ₹1L in Vested = declare. Non-declaration = black money under law. Declare honestly!" },
    { question: "What is FATCA and why do brokers ask?", answer: "FATCA (Foreign Account Tax Compliance Act) = US law to prevent tax evasion. Indian brokers ask: Are you US person? (citizen, green card holder). If YES: Your account info shared with US IRS (tax implications in US + India). If NO: No issue. All global investors must answer FATCA questions (KYC requirement)." },
    { question: "Can NRI invest in US stocks?", answer: "YES! NRI can: (1) Open Vested/Groww US account (easier than residents!), (2) Transfer $ from NRE account (no LRS limit for NRI using foreign funds), (3) If using Indian funds (NRO): LRS limit applies ($250K). Tax: (1) In USA: 30% on gains (TDS), (2) In India: If Indian resident for tax purposes. File taxes in both countries!" },
    { question: "Is international investing worth it for small investors?", answer: "Depends! Small (below ₹10L portfolio): Focus on India first (higher growth, no currency risk, simpler taxes). Medium (₹10-50L): Add 10-20% international (diversification). Large (₹50L+): 20-30% international (global exposure, currency hedge). Start international only after: (1) Emergency fund ready, (2) Indian equity allocation complete, (3) Understand currency/tax implications." }
  ];

  return (<><SEOHelmet title="Global Investing 2025: US Stocks, International Mutual Funds, LRS India Complete Guide | MoneyCal" description="Invest globally from India: US stocks via Vested/Groww ($250K LRS limit), international mutual funds (Nasdaq 100, S&P 500), currency risk, taxation (debt fund rules), FATCA, foreign asset declaration in ITR. Hindi + English" keywords="global investing India 2025, US stocks from India, international mutual funds, LRS limit, Vested Groww, currency risk, foreign assets ITR, वैश्विक निवेश गाइड" url="/learn/advanced-specialised-finance/global-investing-us-stocks-international-mutual-funds-lrs-india-2025" faqData={faqData} />
      <div className="min-h-screen bg-gradient-to-br from-green-50 via-emerald-50 to-teal-50"><header className="bg-white shadow-md sticky top-0 z-50 border-b"><div className="max-w-7xl mx-auto px-4 py-4"><div className="flex items-center justify-between"><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 text-gray-600 hover:text-green-600 transition-colors"><ArrowLeft className="w-5 h-5" /><span className="hidden sm:inline">Back</span></Link><div className="flex items-center gap-4"><span className="hidden sm:inline text-sm text-gray-600">Lesson 3 of 7</span><Link to="/learn/advanced-specialised-finance" className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"><span className="hidden sm:inline">Hub</span><ArrowRight className="w-5 h-5" /></Link></div></div></div></header>
        <div className="max-w-4xl mx-auto px-4 py-12"><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-12"><div className="flex items-center gap-3 mb-4"><div className="p-3 bg-gradient-to-r from-green-500 to-emerald-600 rounded-xl shadow-lg"><Globe className="w-8 h-8 text-white" /></div><div><div className="text-sm font-semibold text-green-600 uppercase tracking-wide">Lesson 3 • 55 Minutes • Advanced</div><h1 className="text-4xl font-bold text-gray-900">Global Investing 2025</h1><p className="text-xl text-gray-600 mt-1">US Stocks, International MF, LRS</p></div></div></motion.div>
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12"><div className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100"><h2 className="text-3xl font-bold mb-6 text-gray-900 flex items-center gap-3"><HelpCircle className="w-8 h-8 text-blue-600" />❓ FAQs</h2><div className="space-y-6">{faqData.map((faq, index) => (<div key={index} className="border-b border-gray-200 pb-6 last:border-0"><h3 className="font-bold text-lg text-gray-900 mb-2">Q{index + 1}: {faq.question}</h3><p className="text-gray-700">{faq.answer}</p></div>))}</div></div></motion.section>
          <div className="bg-gradient-to-r from-green-600 to-emerald-600 rounded-2xl p-8 text-white shadow-2xl text-center"><Award className="w-12 h-12 mx-auto mb-4" /><h3 className="text-3xl font-bold mb-4">🎉 Done!</h3><Link to="/learn/advanced-specialised-finance" className="inline-flex items-center gap-3 px-8 py-4 bg-white text-green-600 rounded-xl font-bold text-lg hover:shadow-2xl transition-all">Next<ArrowRight className="w-6 h-6" /></Link></div>
        </div>
      </div>
    </>
  );
};

export default GlobalInvesting;
