import React, { useState, useMemo } from 'react';
import { Home, IndianRupee, TrendingUp, DollarSign, Calendar, Info, Download, Share2, ArrowRight } from 'lucide-react';
import SEOHelmet from '../components/SEOHelmet';

const HomeLoanEmiCalculator: React.FC = () => {
  const [loanAmount, setLoanAmount] = useState(5000000);
  const [interestRate, setInterestRate] = useState(8.5);
  const [loanTenure, setLoanTenure] = useState(20);
  const [tenureType, setTenureType] = useState<'years' | 'months'>('years');

  const calculations = useMemo(() => {
    const principal = loanAmount;
    const monthlyRate = interestRate / 12 / 100;
    const months = tenureType === 'years' ? loanTenure * 12 : loanTenure;

    // EMI Calculation
    const emi = principal * monthlyRate * Math.pow(1 + monthlyRate, months) / (Math.pow(1 + monthlyRate, months) - 1);
    const totalAmount = emi * months;
    const totalInterest = totalAmount - principal;

    // Amortization schedule
    let balance = principal;
    const schedule = [];

    for (let i = 1; i <= Math.min(months, 12); i++) {
      const interestPayment = balance * monthlyRate;
      const principalPayment = emi - interestPayment;
      balance -= principalPayment;

      schedule.push({
        month: i,
        emi: emi,
        principal: principalPayment,
        interest: interestPayment,
        balance: balance > 0 ? balance : 0
      });
    }

    return {
      emi: Math.round(emi),
      totalAmount: Math.round(totalAmount),
      totalInterest: Math.round(totalInterest),
      principal,
      schedule
    };
  }, [loanAmount, interestRate, loanTenure, tenureType]);

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0
    }).format(amount);
  };

  const downloadSchedule = () => {
    const content = `
HOME LOAN EMI Calculator REPORT
═══════════════════════════════════════════════════

LOAN DETAILS:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Loan Amount:           ${formatCurrency(loanAmount)}
Interest Rate:         ${interestRate}% per annum
Loan Tenure:           ${loanTenure} ${tenureType}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

MONTHLY EMI:           ${formatCurrency(calculations.emi)}
Total Payment:         ${formatCurrency(calculations.totalAmount)}
Total Interest:        ${formatCurrency(calculations.totalInterest)}
Principal Amount:      ${formatCurrency(calculations.principal)}

FIRST 12 MONTHS BREAKDOWN:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Month | EMI | Principal | Interest | Balance
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${calculations.schedule.map(row =>
      `${row.month.toString().padStart(2)} | ${formatCurrency(row.emi)} | ${formatCurrency(row.principal)} | ${formatCurrency(row.interest)} | ${formatCurrency(row.balance)}`
    ).join('\n')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by MoneyCal.in - Home Loan EMI Calculator
https://moneycal.in/calculators/home-loan-emi-calculator
Date: ${new Date().toLocaleDateString('en-IN')}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Home-Loan-EMI-Report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
  };

  return (
    <>
      <SEOHelmet
        title="Home Loan EMI Calculator 2025 India - Calculate Housing Loan EMI, Interest | MoneyCal"
        description="Calculate home loan EMI with our advanced calculator. Get instant results for housing loan monthly payment, total interest, amortization schedule. Compare SBI, HDFC, ICICI home loan rates 2025. Tax benefits Calculator included."
        keywords="home loan EMI Calculator, housing loan Calculator India, home loan interest Calculator, EMI Calculator 2025, SBI home loan, HDFC housing loan, home loan tax benefit, property loan EMI, house loan calculator"
        canonicalUrl="https://moneycal.in/calculators/home-loan-emi-calculator"
        structuredData={{
          '@context': 'https://schema.org',
          '@type': 'WebApplication',
          name: 'Home Loan EMI Calculator India',
          description: 'Calculate home loan EMI, total interest, and repayment schedule for housing loans in India',
          applicationCategory: 'FinanceApplication',
          offers: {
            '@type': 'Offer',
            price: '0',
            priceCurrency: 'INR'
          }
        }}
      />

      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 py-8">
        <div className="max-w-7xl mx-auto px-4">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="flex items-center justify-center mb-4">
              <Home className="h-16 w-16 text-blue-600 mr-4" />
              <h1 className="text-5xl font-black bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">
                Home Loan EMI Calculator
              </h1>
            </div>
            <p className="text-xl text-gray-700 max-w-3xl mx-auto">
              Calculate your home loan monthly EMI, total interest, and repayment schedule with tax benefits
            </p>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Input Section */}
            <div className="lg:col-span-1">
              <div className="bg-white rounded-2xl shadow-2xl p-8 sticky top-8">
                <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
                  <IndianRupee className="h-6 w-6 mr-2 text-blue-600" />
                  Loan Details
                </h2>

                {/* Loan Amount */}
                <div className="mb-6">
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Loan Amount (Principal)
                  </label>
                  <input
                    type="number"
                    aria-label="Home loan amount in rupees"
                    value={loanAmount}
                    onChange={(e) => setLoanAmount(Number(e.target.value))}
                    className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-lg font-bold"
                  />
                  <input
                    type="range"
                    aria-label="Adjust home loan amount"
                    min="100000"
                    max="50000000"
                    step="100000"
                    value={loanAmount}
                    onChange={(e) => setLoanAmount(Number(e.target.value))}
                    className="w-full mt-3"
                  />
                  <div className="flex justify-between text-xs text-gray-600 mt-1">
                    <span>₹1L</span>
                    <span className="font-bold text-blue-600">{formatCurrency(loanAmount)}</span>
                    <span>₹5Cr</span>
                  </div>
                </div>

                {/* Interest Rate */}
                <div className="mb-6">
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Interest Rate (% per annum)
                  </label>
                  <input
                    type="number"
                    aria-label="Annual interest rate percentage"
                    value={interestRate}
                    onChange={(e) => setInterestRate(Number(e.target.value))}
                    step="0.1"
                    className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-lg font-bold"
                  />
                  <input
                    type="range"
                    aria-label="Adjust interest rate"
                    min="5"
                    max="15"
                    step="0.1"
                    value={interestRate}
                    onChange={(e) => setInterestRate(Number(e.target.value))}
                    className="w-full mt-3"
                  />
                  <div className="flex justify-between text-xs text-gray-600 mt-1">
                    <span>5%</span>
                    <span className="font-bold text-blue-600">{interestRate}%</span>
                    <span>15%</span>
                  </div>
                </div>

                {/* Loan Tenure */}
                <div className="mb-6">
                  <label className="block text-sm font-semibold text-gray-700 mb-2">
                    Loan Tenure
                  </label>
                  <div className="flex gap-2 mb-3">
                    <button
                      onClick={() => setTenureType('years')}
                      className={`flex-1 py-2 px-4 rounded-xl font-bold transition-all ${tenureType === 'years'
                          ? 'bg-blue-600 text-white'
                          : 'bg-gray-200 text-gray-700'
                        }`}
                    >
                      Years
                    </button>
                    <button
                      onClick={() => setTenureType('months')}
                      className={`flex-1 py-2 px-4 rounded-xl font-bold transition-all ${tenureType === 'months'
                          ? 'bg-blue-600 text-white'
                          : 'bg-gray-200 text-gray-700'
                        }`}
                    >
                      Months
                    </button>
                  </div>
                  <input
                    type="number"
                    aria-label="Loan tenure duration"
                    value={loanTenure}
                    onChange={(e) => setLoanTenure(Number(e.target.value))}
                    className="w-full px-4 py-3 border-2 border-gray-300 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-lg font-bold"
                  />
                  <input
                    type="range"
                    aria-label="Adjust loan tenure"
                    min={tenureType === 'years' ? 1 : 12}
                    max={tenureType === 'years' ? 30 : 360}
                    value={loanTenure}
                    onChange={(e) => setLoanTenure(Number(e.target.value))}
                    className="w-full mt-3"
                  />
                  <div className="flex justify-between text-xs text-gray-600 mt-1">
                    <span>{tenureType === 'years' ? '1 Yr' : '12 Mo'}</span>
                    <span className="font-bold text-blue-600">{loanTenure} {tenureType === 'years' ? 'Years' : 'Months'}</span>
                    <span>{tenureType === 'years' ? '30 Yr' : '360 Mo'}</span>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="grid grid-cols-2 gap-3">
                  <button
                    onClick={downloadSchedule}
                    className="py-3 px-4 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-xl font-bold hover:shadow-lg transition-all flex items-center justify-center"
                  >
                    <Download className="h-5 w-5 mr-2" />
                    Download
                  </button>
                  <button
                    onClick={() => {
                      navigator.share?.({
                        title: 'Home Loan EMI Calculator',
                        text: `My Home Loan EMI: ${formatCurrency(calculations.emi)}/month`,
                        url: window.location.href
                      });
                    }}
                    className="py-3 px-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-xl font-bold hover:shadow-lg transition-all flex items-center justify-center"
                  >
                    <Share2 className="h-5 w-5 mr-2" />
                    Share
                  </button>
                </div>
              </div>
            </div>

            {/* Results Section */}
            <div className="lg:col-span-2 space-y-6">
              {/* EMI Result */}
              <div className="bg-gradient-to-br from-blue-600 to-purple-600 rounded-2xl shadow-2xl p-8 text-white">
                <h2 className="text-2xl font-bold mb-6 flex items-center">
                  <Calendar className="h-7 w-7 mr-3" />
                  Your Monthly EMI
                </h2>
                <div className="text-6xl font-black mb-2">
                  {formatCurrency(calculations.emi)}
                </div>
                <p className="text-xl text-blue-100">
                  Pay this amount every month for {tenureType === 'years' ? loanTenure + ' years' : loanTenure + ' months'}
                </p>
              </div>

              {/* Breakdown Cards */}
              <div className="grid md:grid-cols-3 gap-6">
                <div className="bg-white rounded-2xl shadow-xl p-6 border-2 border-blue-200">
                  <DollarSign className="h-12 w-12 text-blue-600 mb-3" />
                  <h3 className="text-sm font-semibold text-gray-600 mb-2">Principal Amount</h3>
                  <p className="text-3xl font-black text-gray-900">{formatCurrency(calculations.principal)}</p>
                </div>

                <div className="bg-white rounded-2xl shadow-xl p-6 border-2 border-orange-200">
                  <TrendingUp className="h-12 w-12 text-orange-600 mb-3" />
                  <h3 className="text-sm font-semibold text-gray-600 mb-2">Total Interest</h3>
                  <p className="text-3xl font-black text-gray-900">{formatCurrency(calculations.totalInterest)}</p>
                </div>

                <div className="bg-white rounded-2xl shadow-xl p-6 border-2 border-purple-200">
                  <IndianRupee className="h-12 w-12 text-purple-600 mb-3" />
                  <h3 className="text-sm font-semibold text-gray-600 mb-2">Total Payment</h3>
                  <p className="text-3xl font-black text-gray-900">{formatCurrency(calculations.totalAmount)}</p>
                </div>
              </div>

              {/* Pie Chart Visualization */}
              <div className="bg-white rounded-2xl shadow-xl p-8">
                <h3 className="text-2xl font-bold text-gray-900 mb-6">Payment Breakdown</h3>
                <div className="flex items-center justify-center mb-8">
                  <div className="relative w-64 h-64">
                    <svg viewBox="0 0 100 100" className="transform -rotate-90">
                      {/* Principal */}
                      <circle
                        cx="50"
                        cy="50"
                        r="40"
                        fill="none"
                        stroke="#3b82f6"
                        strokeWidth="20"
                        strokeDasharray={`${(calculations.principal / calculations.totalAmount) * 251.2} 251.2`}
                      />
                      {/* Interest */}
                      <circle
                        cx="50"
                        cy="50"
                        r="40"
                        fill="none"
                        stroke="#f97316"
                        strokeWidth="20"
                        strokeDasharray={`${(calculations.totalInterest / calculations.totalAmount) * 251.2} 251.2`}
                        strokeDashoffset={`-${(calculations.principal / calculations.totalAmount) * 251.2}`}
                      />
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center flex-col">
                      <span className="text-4xl font-black text-gray-900">
                        {Math.round((calculations.totalInterest / calculations.totalAmount) * 100)}%
                      </span>
                      <span className="text-sm text-gray-600">Interest</span>
                    </div>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="flex items-center gap-3">
                    <div className="w-6 h-6 bg-blue-600 rounded"></div>
                    <div>
                      <p className="text-sm text-gray-600">Principal</p>
                      <p className="font-bold text-gray-900">{formatCurrency(calculations.principal)}</p>
                      <p className="text-xs text-gray-500">
                        {Math.round((calculations.principal / calculations.totalAmount) * 100)}% of total
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="w-6 h-6 bg-orange-600 rounded"></div>
                    <div>
                      <p className="text-sm text-gray-600">Interest</p>
                      <p className="font-bold text-gray-900">{formatCurrency(calculations.totalInterest)}</p>
                      <p className="text-xs text-gray-500">
                        {Math.round((calculations.totalInterest / calculations.totalAmount) * 100)}% of total
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Amortization Schedule */}
              <div className="bg-white rounded-2xl shadow-xl p-8">
                <h3 className="text-2xl font-bold text-gray-900 mb-6">First Year Payment Schedule</h3>
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="bg-gradient-to-r from-blue-600 to-purple-600 text-white">
                        <th className="py-3 px-4 text-left rounded-tl-xl">Month</th>
                        <th className="py-3 px-4 text-right">EMI</th>
                        <th className="py-3 px-4 text-right">Principal</th>
                        <th className="py-3 px-4 text-right">Interest</th>
                        <th className="py-3 px-4 text-right rounded-tr-xl">Balance</th>
                      </tr>
                    </thead>
                    <tbody>
                      {calculations.schedule.map((row, idx) => (
                        <tr key={row.month} className={idx % 2 === 0 ? 'bg-gray-50' : 'bg-white'}>
                          <td className="py-3 px-4 font-semibold text-gray-900">{row.month}</td>
                          <td className="py-3 px-4 text-right font-bold text-blue-600">{formatCurrency(row.emi)}</td>
                          <td className="py-3 px-4 text-right text-gray-900">{formatCurrency(row.principal)}</td>
                          <td className="py-3 px-4 text-right text-orange-600">{formatCurrency(row.interest)}</td>
                          <td className="py-3 px-4 text-right text-gray-700">{formatCurrency(row.balance)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>

              {/* Info Cards */}
              <div className="bg-gradient-to-r from-green-50 to-emerald-50 rounded-2xl p-6 border-2 border-green-200">
                <h3 className="text-xl font-bold text-green-800 mb-4 flex items-center">
                  <Info className="h-6 w-6 mr-2" />
                  Tax Benefits on Home Loan
                </h3>
                <ul className="space-y-3 text-gray-800">
                  <li className="flex items-start">
                    <span className="text-green-600 mr-2">✓</span>
                    <span><strong>Section 80C:</strong> Principal repayment up to ₹1.5 lakh deduction</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-green-600 mr-2">✓</span>
                    <span><strong>Section 24(b):</strong> Interest payment up to ₹2 lakh deduction</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-green-600 mr-2">✓</span>
                    <span><strong>First-time buyers:</strong> Additional ₹50,000 under Section 80EEA</span>
                  </li>
                  <li className="flex items-start">
                    <span className="text-green-600 mr-2">✓</span>
                    <span><strong>Total potential saving:</strong> Up to ₹3.5 lakh per year</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* FAQ */}
          <div className="mt-16 bg-white rounded-2xl shadow-xl p-8">
            <h2 className="text-3xl font-bold text-gray-900 mb-8">Frequently Asked Questions (FAQ)</h2>
            <div className="space-y-6">
              {[
                {
                  q: 'How is home loan EMI calculated?',
                  a: 'EMI is calculated using the formula: EMI = [P × R × (1+R)^N] / [(1+R)^N-1], where P = Principal, R = Monthly interest rate, N = Number of months. This ensures equal monthly payments throughout the loan tenure.'
                },
                {
                  q: 'What is the current home loan interest rate in India 2025?',
                  a: 'Home loan interest rates in India range from 8.0% to 11.5% per annum. SBI offers rates starting at 8.50%, HDFC at 8.60%, ICICI at 8.75%, and Axis Bank at 8.80%. Rates vary based on credit score, loan amount, and tenure.'
                },
                {
                  q: 'How much home loan can I get on ₹50,000 salary?',
                  a: 'With a monthly salary of ₹50,000, you can typically get a home loan of ₹35-40 lakhs. Banks use 60× salary multiplier. Your EMI should not exceed 40-50% of your monthly income (₹20,000-25,000).'
                },
                {
                  q: 'What tax benefits are available on home loans?',
                  a: 'Section 80C: ₹1.5L deduction on principal. Section 24(b): ₹2L deduction on interest. Section 80EEA: Additional ₹50K for first-time buyers. Total potential tax savings: ₹3.5 lakh per year.'
                },
                {
                  q: 'Should I choose floating or fixed interest rate?',
                  a: 'Floating rates (8.5-9%) are lower but fluctuate with market. Fixed rates (9-10%) remain constant. Choose floating if rates are expected to fall, fixed if you want certainty. Most borrowers prefer floating rates.'
                },
                {
                  q: 'How to reduce home loan EMI burden?',
                  a: '1) Make lump-sum prepayments, 2) Increase tenure slightly, 3) Negotiate lower interest rates, 4) Transfer to lower-rate lender, 5) Claim full tax benefits, 6) Avoid loan moratoriums.'
                }
              ].map((faq, idx) => (
                <div key={idx} className="bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl p-6 border-2 border-blue-200">
                  <h3 className="font-bold text-lg text-gray-900 mb-3">{faq.q}</h3>
                  <p className="text-gray-700 leading-relaxed">{faq.a}</p>
                </div>
              ))}
            </div>
          </div>

          {/* External Links */}
          <div className="mt-8 bg-blue-100 p-6 rounded-xl border-2 border-blue-300">
            <p className="text-sm text-gray-800">
              <strong>📚 External Resources:</strong>{' '}
              <a href="https://sbi.co.in/web/personal-banking/loans/home-loans" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                SBI Home Loans
              </a>
              {' | '}
              <a href="https://www.hdfcbank.com/personal/borrow/popular-loans/home-loan" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                HDFC Home Loans
              </a>
              {' | '}
              <a href="https://www.icicibank.com/personal-banking/loans/home-loan" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                ICICI Home Loans
              </a>
              {' | '}
              <a href="https://en.wikipedia.org/wiki/Home_loan" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:underline">
                Home Loan (Wikipedia)
              </a>
            </p>
          </div>

          {/* Related Tools */}
          <div className="mt-12 bg-gradient-to-r from-purple-50 to-pink-50 rounded-2xl p-8 border-2 border-purple-200">
            <h3 className="text-2xl font-bold text-gray-900 mb-6">🔗 Related Loan Calculators</h3>
            <div className="grid md:grid-cols-3 gap-4">
              {[
                { name: 'Personal Loan EMI', path: '/calculators/personal-loan-emi-calculator', icon: '💵' },
                { name: 'Car Loan EMI', path: '/calculators/car-loan-emi-calculator', icon: '🚗' },
                { name: 'Loan Comparison', path: '/calculators/loan-comparison-calculator', icon: '📊' },
                { name: 'Prepayment Calculator', path: '/loan-tools/prepayment-calculator', icon: '💰' },
                { name: 'Loan Eligibility', path: '/loan-tools/loan-affordability', icon: '✅' },
                { name: 'Property Calculator', path: '/calculators/property-registration-calculator', icon: '🏘️' }
              ].map((tool, idx) => (
                <a
                  key={idx}
                  href={tool.path}
                  className="flex items-center gap-3 p-4 bg-white rounded-xl hover:shadow-lg transition-all border-2 border-purple-200 hover:border-purple-500"
                >
                  <span className="text-3xl">{tool.icon}</span>
                  <div>
                    <h4 className="font-bold text-gray-900">{tool.name}</h4>
                    <ArrowRight className="h-4 w-4 text-purple-600" />
                  </div>
                </a>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default HomeLoanEmiCalculator;

