import React, { useState } from 'react';
import { Helmet } from 'react-helmet';

const CATEGORY = 'Retirement & Pension';

const defaultContribution = 5000;
const defaultYears = 25;
const defaultReturn = 10;
const defaultTier = 'Tier I';

function calculateNpsMaturity(P: number, r: number, n: number) {
  // P = monthly contribution, r = annual return %, n = years
  const months = n * 12;
  const monthlyRate = r / 12 / 100;
  return P * ((Math.pow(1 + monthlyRate, months) - 1) / monthlyRate) * (1 + monthlyRate);
}

const NpsReturnCalculator: React.FC = () => {
  const [contribution, setContribution] = useState(defaultContribution);
  const [years, setYears] = useState(defaultYears);
  const [expectedReturn, setExpectedReturn] = useState(defaultReturn);
  const [tier, setTier] = useState(defaultTier);

  const maturity = calculateNpsMaturity(contribution, expectedReturn, years);
  const totalInvested = contribution * 12 * years;
  const totalGain = maturity - totalInvested;

  return (
    <div className="max-w-2xl mx-auto p-4 bg-white rounded shadow mt-6">
      <Helmet>
        <title>NPS Return Calculator India – Estimate National Pension System Returns</title>
        <meta name="description" content="Estimate your NPS maturity amount, total investment, and returns. Use our NPS Return Calculator for Tier I & II, tailored for Indian users. Free, fast, and accurate!" />
        <link rel="canonical" href="https://moneycal.in/calculators/nps-return-calculator" />
        <meta property="og:title" content="NPS Return Calculator India – Estimate National Pension System Returns" />
        <meta property="og:description" content="Estimate your NPS maturity amount, total investment, and returns. Use our NPS Return Calculator for Tier I & II, tailored for Indian users. Free, fast, and accurate!" />
      </Helmet>
      <h1 className="text-2xl font-bold mb-2">NPS Return Calculator India</h1>
      <p className="mb-4 text-gray-700">Calculate your National Pension System (NPS) maturity amount, total investment, and estimated returns. Supports Tier I and Tier II accounts, tailored for Indian investors.</p>
      <form className="grid grid-cols-1 gap-4 mb-6">
        <label>
          Monthly Contribution (₹)
          <input type="number" min={500} value={contribution} onChange={e => setContribution(Number(e.target.value))} className="input input-bordered w-full" />
        </label>
        <label>
          Investment Duration (years)
          <input type="number" min={1} max={40} value={years} onChange={e => setYears(Number(e.target.value))} className="input input-bordered w-full" />
        </label>
        <label>
          Expected Annual Return (%)
          <input type="number" min={4} max={15} step={0.1} value={expectedReturn} onChange={e => setExpectedReturn(Number(e.target.value))} className="input input-bordered w-full" />
        </label>
        <label>
          NPS Account Type
          <select value={tier} onChange={e => setTier(e.target.value)} className="input input-bordered w-full">
            <option value="Tier I">Tier I</option>
            <option value="Tier II">Tier II</option>
          </select>
        </label>
      </form>
      <div className="bg-gray-50 p-4 rounded mb-6">
        <h2 className="font-semibold mb-2">Results</h2>
        <p><strong>Maturity Amount:</strong> ₹{maturity ? maturity.toLocaleString(undefined, { maximumFractionDigits: 2 }) : 0}</p>
        <p><strong>Total Invested:</strong> ₹{totalInvested ? totalInvested.toLocaleString(undefined, { maximumFractionDigits: 2 }) : 0}</p>
        <p><strong>Total Gain:</strong> ₹{totalGain ? totalGain.toLocaleString(undefined, { maximumFractionDigits: 2 }) : 0}</p>
      </div>
      <div className="mb-8">
        <h2 className="text-xl font-semibold mb-2">About NPS Return Calculator</h2>
        <p className="mb-2">The <strong>National Pension System (NPS)</strong> is a government-backed retirement savings scheme in India, designed to help individuals build a retirement corpus through regular contributions. Our <strong>NPS Return Calculator</strong> helps you estimate your maturity amount, total investment, and returns for both Tier I and Tier II accounts, making retirement planning easier and more transparent.</p>
        <p className="mb-2">To use this calculator, enter your monthly contribution, investment duration, expected annual return, and select your NPS account type. The tool instantly shows your projected maturity value, total invested amount, and total gain, helping you make informed decisions about your retirement savings.</p>
        <p className="mb-2">NPS offers attractive tax benefits under Section 80CCD(1), 80CCD(1B), and 80CCD(2) for Tier I accounts. Tier II accounts offer more flexibility but do not provide tax benefits. The maturity amount depends on your contribution, investment period, and the returns generated by your chosen NPS funds.</p>
        <p className="mb-2">Use this calculator to compare different contribution scenarios, optimize your retirement planning, and maximize your NPS benefits. For more details, read our guide on <a href="/blog/nps-benefits-india" className="text-blue-600 underline">NPS benefits and rules in India</a>.</p>
      </div>
      <div className="mb-8">
        <h2 className="text-lg font-semibold mb-2">Frequently Asked Questions (FAQ)</h2>
        <details className="mb-2"><summary>How is NPS maturity amount calculated?</summary><div className="pl-4">NPS maturity is calculated using the future value of a recurring investment formula, considering monthly contributions, expected annual return, and investment duration.</div></details>
        <details className="mb-2"><summary>What is the minimum contribution for NPS?</summary><div className="pl-4">For Tier I, the minimum annual contribution is ₹1,000. For Tier II, there is no minimum annual contribution.</div></details>
        <details className="mb-2"><summary>Are NPS returns guaranteed?</summary><div className="pl-4">No, NPS returns are market-linked and depend on the performance of the chosen pension funds. Past performance does not guarantee future returns.</div></details>
        <details className="mb-2"><summary>What are the tax benefits of NPS?</summary><div className="pl-4">Tier I NPS contributions are eligible for tax deductions under Section 80CCD(1), 80CCD(1B), and 80CCD(2) of the Income Tax Act.</div></details>
      </div>
      <div className="mb-8">
        <h3 className="font-semibold">Related Calculators</h3>
        <ul className="list-disc list-inside">
          <li><a href="/calculators/retirement-calculator" className="text-blue-600 underline">Retirement Calculator</a></li>
          <li><a href="/calculators/pension-calculator" className="text-blue-600 underline">Pension Calculator</a></li>
          <li><a href="/calculators/ppf-calculator" className="text-blue-600 underline">PPF Calculator</a></li>
        </ul>
      </div>
      {/* FAQ Schema for SEO */}
      <script type="application/ld+json">
        {JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          'mainEntity': [
            {
              '@type': 'Question',
              'name': 'How is NPS maturity amount calculated?',
              'acceptedAnswer': {
                '@type': 'Answer',
                'text': 'NPS maturity is calculated using the future value of a recurring investment formula, considering monthly contributions, expected annual return, and investment duration.'
              }
            },
            {
              '@type': 'Question',
              'name': 'What is the minimum contribution for NPS?',
              'acceptedAnswer': {
                '@type': 'Answer',
                'text': 'For Tier I, the minimum annual contribution is ₹1,000. For Tier II, there is no minimum annual contribution.'
              }
            },
            {
              '@type': 'Question',
              'name': 'Are NPS returns guaranteed?',
              'acceptedAnswer': {
                '@type': 'Answer',
                'text': 'No, NPS returns are market-linked and depend on the performance of the chosen pension funds. Past performance does not guarantee future returns.'
              }
            },
            {
              '@type': 'Question',
              'name': 'What are the tax benefits of NPS?',
              'acceptedAnswer': {
                '@type': 'Answer',
                'text': 'Tier I NPS contributions are eligible for tax deductions under Section 80CCD(1), 80CCD(1B), and 80CCD(2) of the Income Tax Act.'
              }
            }
          ]
        })}
      </script>
      {/* Category tag for SEO */}
      <meta name="category" content={CATEGORY} />
    </div>
  );
};

export default NpsReturnCalculator; 