import React, { useState, useMemo } from 'react';
import { DollarSign, TrendingUp, Calculator, Download, Share2, PieChart, Calendar, Home, Briefcase, Heart, Shield } from 'lucide-react';
import SEOHelmet from '../components/SEOHelmet';
import { Link } from 'react-router-dom';

export const SalaryCalculator: React.FC = () => {
  // Input states
  const [basicSalary, setBasicSalary] = useState(50000);
  const [hra, setHra] = useState(25000);
  const [specialAllowance, setSpecialAllowance] = useState(10000);
  const [otherAllowances, setOtherAllowances] = useState(5000);
  const [bonus, setBonus] = useState(0);
  const [pfContribution, setPfContribution] = useState(12);
  const [professionalTax, setProfessionalTax] = useState(200);
  const [tds, setTds] = useState(5000);
  const [salaryType, setSalaryType] = useState<'monthly' | 'annual'>('monthly');

  // Calculations
  const calculations = useMemo(() => {
    const multiplier = salaryType === 'monthly' ? 1 : 12;
    
    // Gross Salary Components
    const monthlyBasic = basicSalary;
    const monthlyHRA = hra;
    const monthlySpecial = specialAllowance;
    const monthlyOther = otherAllowances;
    const monthlyBonus = bonus / 12;
    
    const grossMonthlySalary = monthlyBasic + monthlyHRA + monthlySpecial + monthlyOther + monthlyBonus;
    const grossAnnualSalary = grossMonthlySalary * 12;
    
    // Deductions
    const monthlyPF = (monthlyBasic * pfContribution) / 100;
    const employerPF = monthlyPF; // Employer contribution (equal)
    const monthlyProfTax = professionalTax;
    const monthlyTDS = tds;
    const totalMonthlyDeductions = monthlyPF + monthlyProfTax + monthlyTDS;
    
    // Net Salary
    const netMonthlySalary = grossMonthlySalary - totalMonthlyDeductions;
    const netAnnualSalary = netMonthlySalary * 12;
    
    // CTC (Cost to Company)
    const annualBonus = bonus;
    const annualPF = monthlyPF * 12;
    const employerPFAnnual = employerPF * 12;
    const gratuity = (monthlyBasic * 12 * 0.0481); // Approx 4.81% of basic
    const ctc = grossAnnualSalary + employerPFAnnual + gratuity;
    
    // Percentage breakdowns
    const basicPercent = (monthlyBasic / grossMonthlySalary) * 100;
    const hraPercent = (monthlyHRA / grossMonthlySalary) * 100;
    const allowancesPercent = ((monthlySpecial + monthlyOther) / grossMonthlySalary) * 100;
    const deductionsPercent = (totalMonthlyDeductions / grossMonthlySalary) * 100;
    
    // Take-home percentage
    const takeHomePercent = (netMonthlySalary / grossMonthlySalary) * 100;
    
    return {
      grossMonthlySalary: Math.round(grossMonthlySalary),
      grossAnnualSalary: Math.round(grossAnnualSalary),
      netMonthlySalary: Math.round(netMonthlySalary),
      netAnnualSalary: Math.round(netAnnualSalary),
      ctc: Math.round(ctc),
      monthlyPF: Math.round(monthlyPF),
      employerPF: Math.round(employerPF),
      totalMonthlyDeductions: Math.round(totalMonthlyDeductions),
      totalAnnualDeductions: Math.round(totalMonthlyDeductions * 12),
      gratuity: Math.round(gratuity),
      basicPercent: Math.round(basicPercent),
      hraPercent: Math.round(hraPercent),
      allowancesPercent: Math.round(allowancesPercent),
      deductionsPercent: Math.round(deductionsPercent),
      takeHomePercent: Math.round(takeHomePercent)
    };
  }, [basicSalary, hra, specialAllowance, otherAllowances, bonus, pfContribution, professionalTax, tds, salaryType]);

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount);
  };

  const handleDownload = () => {
    const content = `
SALARY BREAKDOWN - MoneyCal.in
Generated: ${new Date().toLocaleDateString('en-IN')}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SALARY STRUCTURE
Basic Salary: ${formatCurrency(basicSalary)}
HRA: ${formatCurrency(hra)}
Special Allowance: ${formatCurrency(specialAllowance)}
Other Allowances: ${formatCurrency(otherAllowances)}
Annual Bonus: ${formatCurrency(bonus)}

GROSS SALARY
Monthly: ${formatCurrency(calculations.grossMonthlySalary)}
Annual: ${formatCurrency(calculations.grossAnnualSalary)}

DEDUCTIONS
PF (Employee): ${formatCurrency(calculations.monthlyPF)} /month
Professional Tax: ${formatCurrency(professionalTax)} /month
TDS: ${formatCurrency(tds)} /month
Total Deductions: ${formatCurrency(calculations.totalMonthlyDeductions)} /month

NET TAKE-HOME SALARY
Monthly: ${formatCurrency(calculations.netMonthlySalary)}
Annual: ${formatCurrency(calculations.netAnnualSalary)}

COST TO COMPANY (CTC)
Annual CTC: ${formatCurrency(calculations.ctc)}

TAKE-HOME: ${calculations.takeHomePercent}% of Gross Salary

Generated by MoneyCal.in - India's #1 Financial Calculator
https://moneycal.in/calculators/salary-calculator
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Salary-Breakdown-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
  };

  const handleShare = async () => {
    const text = `My Salary Breakdown:\n💰 Gross: ${formatCurrency(calculations.grossMonthlySalary)}/month\n✅ Take-Home: ${formatCurrency(calculations.netMonthlySalary)}/month\n📊 CTC: ${formatCurrency(calculations.ctc)}/year\n\nCalculate yours: https://moneycal.in/calculators/salary-calculator`;
    
    if (navigator.share) {
      try {
        await navigator.share({ title: 'Salary Calculator', text });
      } catch (err) {
        console.log('Share failed', err);
      }
    } else {
      navigator.clipboard.writeText(text);
      alert('Salary details copied to clipboard!');
    }
  };

  return (
    <>
      <SEOHelmet
        title="Salary Calculator 2025 India - CTC, Take Home, In-Hand Salary Calculator | MoneyCal"
        description="Free Salary Calculator India 2025. Calculate CTC, gross salary, net take-home, deductions (PF, TDS, Professional Tax). Salary breakdown with tax savings. Compare in-hand salary."
        keywords="salary calculator India, CTC calculator, take home salary calculator, in-hand salary, gross to net salary, salary breakdown, PF calculator, TDS calculator, professional tax"
        canonicalUrl="https://moneycal.in/calculators/salary-calculator"
      />

      {/* JSON-LD Schema */}
      <script type="application/ld+json">
        {JSON.stringify({
          "@context": "https://schema.org",
          "@type": "WebApplication",
          "name": "Salary Calculator India 2025",
          "description": "Calculate your CTC, gross salary, net take-home salary with all deductions including PF, TDS, and Professional Tax",
          "url": "https://moneycal.in/calculators/salary-calculator",
          "applicationCategory": "FinanceApplication",
          "operatingSystem": "Any",
          "offers": {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "INR"
          },
          "author": {
            "@type": "Organization",
            "name": "MoneyCal India",
            "url": "https://moneycal.in"
          }
        })}
      </script>

      <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 py-12">
        <div className="max-w-7xl mx-auto px-4">
          {/* Header */}
          <div className="text-center mb-12">
            <h1 className="text-5xl font-black bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent mb-4">
              💰 Salary Calculator 2025
            </h1>
            <p className="text-xl text-gray-700 mb-2">Calculate CTC, Gross, Net Take-Home Salary with Deductions</p>
            <p className="text-sm text-gray-600">Complete salary breakdown • PF, TDS, Professional Tax • India</p>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Input Section */}
            <div className="lg:col-span-1 space-y-6">
              <div className="bg-white rounded-2xl shadow-2xl p-6">
                <h2 className="text-2xl font-bold mb-6 flex items-center">
                  <Briefcase className="w-6 h-6 mr-2 text-indigo-600" />
                  Salary Components
                </h2>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-semibold mb-2">Basic Salary (Monthly)</label>
                    <input
                      type="number"
                      value={basicSalary}
                      onChange={(e) => setBasicSalary(Number(e.target.value))}
                      className="w-full px-4 py-3 border-2 rounded-xl text-lg font-bold focus:ring-2 focus:ring-indigo-500 outline-none"
                    />
                    <input
                      type="range"
                      min="10000"
                      max="500000"
                      step="1000"
                      value={basicSalary}
                      onChange={(e) => setBasicSalary(Number(e.target.value))}
                      className="w-full mt-2"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">HRA (House Rent Allowance)</label>
                    <input
                      type="number"
                      value={hra}
                      onChange={(e) => setHra(Number(e.target.value))}
                      className="w-full px-4 py-3 border-2 rounded-xl font-bold focus:ring-2 focus:ring-indigo-500 outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">Special Allowance</label>
                    <input
                      type="number"
                      value={specialAllowance}
                      onChange={(e) => setSpecialAllowance(Number(e.target.value))}
                      className="w-full px-4 py-3 border-2 rounded-xl font-bold focus:ring-2 focus:ring-indigo-500 outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">Other Allowances</label>
                    <input
                      type="number"
                      value={otherAllowances}
                      onChange={(e) => setOtherAllowances(Number(e.target.value))}
                      className="w-full px-4 py-3 border-2 rounded-xl font-bold focus:ring-2 focus:ring-indigo-500 outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">Annual Bonus</label>
                    <input
                      type="number"
                      value={bonus}
                      onChange={(e) => setBonus(Number(e.target.value))}
                      className="w-full px-4 py-3 border-2 rounded-xl font-bold focus:ring-2 focus:ring-indigo-500 outline-none"
                    />
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-2xl shadow-2xl p-6">
                <h2 className="text-xl font-bold mb-4 flex items-center">
                  <Shield className="w-5 h-5 mr-2 text-red-600" />
                  Deductions
                </h2>

                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-semibold mb-2">PF Contribution (%)</label>
                    <input
                      type="number"
                      value={pfContribution}
                      onChange={(e) => setPfContribution(Number(e.target.value))}
                      step="0.5"
                      max="12"
                      className="w-full px-4 py-3 border-2 rounded-xl font-bold focus:ring-2 focus:ring-red-500 outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">Professional Tax (Monthly)</label>
                    <input
                      type="number"
                      value={professionalTax}
                      onChange={(e) => setProfessionalTax(Number(e.target.value))}
                      className="w-full px-4 py-3 border-2 rounded-xl font-bold focus:ring-2 focus:ring-red-500 outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-semibold mb-2">TDS (Monthly)</label>
                    <input
                      type="number"
                      value={tds}
                      onChange={(e) => setTds(Number(e.target.value))}
                      className="w-full px-4 py-3 border-2 rounded-xl font-bold focus:ring-2 focus:ring-red-500 outline-none"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Results Section */}
            <div className="lg:col-span-2 space-y-6">
              {/* Main Results */}
              <div className="grid md:grid-cols-2 gap-6">
                <div className="bg-gradient-to-br from-green-600 to-emerald-600 rounded-2xl shadow-2xl p-8 text-white">
                  <div className="flex items-center justify-between mb-4">
                    <h2 className="text-2xl font-bold">Monthly Take-Home</h2>
                    <DollarSign className="h-12 w-12" />
                  </div>
                  <div className="text-6xl font-black mb-2">{formatCurrency(calculations.netMonthlySalary)}</div>
                  <p className="text-green-100 text-lg">{calculations.takeHomePercent}% of Gross Salary</p>
                </div>

                <div className="bg-gradient-to-br from-blue-600 to-indigo-600 rounded-2xl shadow-2xl p-8 text-white">
                  <div className="flex items-center justify-between mb-4">
                    <h2 className="text-2xl font-bold">Annual CTC</h2>
                    <TrendingUp className="h-12 w-12" />
                  </div>
                  <div className="text-6xl font-black mb-2">{formatCurrency(calculations.ctc)}</div>
                  <p className="text-blue-100 text-lg">Cost to Company</p>
                </div>
              </div>

              {/* Detailed Breakdown */}
              <div className="grid md:grid-cols-3 gap-4">
                <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-indigo-200">
                  <Briefcase className="h-10 w-10 text-indigo-600 mb-3" />
                  <h3 className="text-sm font-semibold text-gray-600 mb-2">Gross Monthly</h3>
                  <p className="text-3xl font-black text-gray-900">{formatCurrency(calculations.grossMonthlySalary)}</p>
                </div>

                <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-red-200">
                  <Shield className="h-10 w-10 text-red-600 mb-3" />
                  <h3 className="text-sm font-semibold text-gray-600 mb-2">Total Deductions</h3>
                  <p className="text-3xl font-black text-gray-900">{formatCurrency(calculations.totalMonthlyDeductions)}</p>
                </div>

                <div className="bg-white rounded-xl shadow-lg p-6 border-2 border-purple-200">
                  <Calendar className="h-10 w-10 text-purple-600 mb-3" />
                  <h3 className="text-sm font-semibold text-gray-600 mb-2">Annual Take-Home</h3>
                  <p className="text-3xl font-black text-gray-900">{formatCurrency(calculations.netAnnualSalary)}</p>
                </div>
              </div>

              {/* Salary Breakdown Chart */}
              <div className="bg-white rounded-2xl shadow-2xl p-8">
                <h3 className="text-2xl font-bold mb-6 flex items-center">
                  <PieChart className="w-6 h-6 mr-2 text-purple-600" />
                  Salary Component Breakdown
                </h3>

                <div className="space-y-4">
                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="font-semibold">Basic Salary</span>
                      <span className="font-bold text-indigo-600">{calculations.basicPercent}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-4">
                      <div className="bg-indigo-600 h-4 rounded-full" style={{ width: `${calculations.basicPercent}%` }}></div>
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="font-semibold">HRA</span>
                      <span className="font-bold text-blue-600">{calculations.hraPercent}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-4">
                      <div className="bg-blue-600 h-4 rounded-full" style={{ width: `${calculations.hraPercent}%` }}></div>
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="font-semibold">Allowances</span>
                      <span className="font-bold text-green-600">{calculations.allowancesPercent}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-4">
                      <div className="bg-green-600 h-4 rounded-full" style={{ width: `${calculations.allowancesPercent}%` }}></div>
                    </div>
                  </div>

                  <div>
                    <div className="flex justify-between mb-2">
                      <span className="font-semibold">Deductions</span>
                      <span className="font-bold text-red-600">{calculations.deductionsPercent}%</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-4">
                      <div className="bg-red-600 h-4 rounded-full" style={{ width: `${calculations.deductionsPercent}%` }}></div>
                    </div>
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-4 mt-8">
                  <button
                    onClick={handleDownload}
                    className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-indigo-600 text-white rounded-xl font-bold hover:bg-indigo-700 active:scale-95 transition-all"
                  >
                    <Download className="w-5 h-5" />
                    Download Report
                  </button>
                  <button
                    onClick={handleShare}
                    className="flex-1 flex items-center justify-center gap-2 px-6 py-3 bg-purple-600 text-white rounded-xl font-bold hover:bg-purple-700 active:scale-95 transition-all"
                  >
                    <Share2 className="w-5 h-5" />
                    Share Results
                  </button>
                </div>
              </div>

              {/* Detailed Breakdown Table */}
              <div className="bg-white rounded-2xl shadow-2xl p-8">
                <h3 className="text-2xl font-bold mb-6">Detailed Salary Structure</h3>
                
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead className="bg-indigo-50">
                      <tr>
                        <th className="px-4 py-3 text-left font-bold text-gray-900">Component</th>
                        <th className="px-4 py-3 text-right font-bold text-gray-900">Monthly</th>
                        <th className="px-4 py-3 text-right font-bold text-gray-900">Annual</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y">
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold">Basic Salary</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(basicSalary)}</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(basicSalary * 12)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold">HRA</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(hra)}</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(hra * 12)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold">Special Allowance</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(specialAllowance)}</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(specialAllowance * 12)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold">Other Allowances</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(otherAllowances)}</td>
                        <td className="px-4 py-3 text-right">{formatCurrency(otherAllowances * 12)}</td>
                      </tr>
                      <tr className="bg-green-50 font-bold">
                        <td className="px-4 py-3">Gross Salary</td>
                        <td className="px-4 py-3 text-right text-green-700">{formatCurrency(calculations.grossMonthlySalary)}</td>
                        <td className="px-4 py-3 text-right text-green-700">{formatCurrency(calculations.grossAnnualSalary)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold text-red-600">Employee PF ({pfContribution}%)</td>
                        <td className="px-4 py-3 text-right text-red-600">-{formatCurrency(calculations.monthlyPF)}</td>
                        <td className="px-4 py-3 text-right text-red-600">-{formatCurrency(calculations.monthlyPF * 12)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold text-red-600">Professional Tax</td>
                        <td className="px-4 py-3 text-right text-red-600">-{formatCurrency(professionalTax)}</td>
                        <td className="px-4 py-3 text-right text-red-600">-{formatCurrency(professionalTax * 12)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold text-red-600">TDS</td>
                        <td className="px-4 py-3 text-right text-red-600">-{formatCurrency(tds)}</td>
                        <td className="px-4 py-3 text-right text-red-600">-{formatCurrency(tds * 12)}</td>
                      </tr>
                      <tr className="bg-blue-50 font-bold">
                        <td className="px-4 py-3">Net Take-Home Salary</td>
                        <td className="px-4 py-3 text-right text-blue-700">{formatCurrency(calculations.netMonthlySalary)}</td>
                        <td className="px-4 py-3 text-right text-blue-700">{formatCurrency(calculations.netAnnualSalary)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold text-green-600">Employer PF</td>
                        <td className="px-4 py-3 text-right text-green-600">+{formatCurrency(calculations.employerPF)}</td>
                        <td className="px-4 py-3 text-right text-green-600">+{formatCurrency(calculations.employerPF * 12)}</td>
                      </tr>
                      <tr className="hover:bg-gray-50">
                        <td className="px-4 py-3 font-semibold text-green-600">Gratuity (Annual)</td>
                        <td className="px-4 py-3 text-right text-green-600">-</td>
                        <td className="px-4 py-3 text-right text-green-600">+{formatCurrency(calculations.gratuity)}</td>
                      </tr>
                      <tr className="bg-purple-50 font-bold text-lg">
                        <td className="px-4 py-4">Cost to Company (CTC)</td>
                        <td className="px-4 py-4 text-right text-purple-700">-</td>
                        <td className="px-4 py-4 text-right text-purple-700">{formatCurrency(calculations.ctc)}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

          {/* Understanding Salary Components */}
          <div className="mt-12 bg-white rounded-2xl shadow-2xl p-8">
            <h2 className="text-3xl font-black mb-6">📚 Understanding Your Salary</h2>
            
            <div className="grid md:grid-cols-2 gap-6">
              <div className="p-6 border-2 border-indigo-200 rounded-xl">
                <h3 className="text-xl font-bold mb-3 text-indigo-700">What is CTC?</h3>
                <p className="text-gray-700 mb-3">
                  CTC (Cost to Company) is the total amount your employer spends on you annually. It includes your gross salary, employer's PF contribution, gratuity, and other benefits.
                </p>
                <p className="text-sm text-gray-600">
                  <strong>Learn more:</strong> <Link to="/learn/what-is-ctc" className="text-indigo-600 hover:underline">Complete CTC Guide</Link>
                </p>
              </div>

              <div className="p-6 border-2 border-green-200 rounded-xl">
                <h3 className="text-xl font-bold mb-3 text-green-700">Take-Home Salary</h3>
                <p className="text-gray-700 mb-3">
                  Your take-home or net salary is the amount you receive in your bank account after all deductions (PF, TDS, Professional Tax).
                </p>
                <p className="text-sm text-gray-600">
                  <strong>Related:</strong> <Link to="/calculators/income-tax-calculator" className="text-green-600 hover:underline">Income Tax Calculator</Link>
                </p>
              </div>

              <div className="p-6 border-2 border-blue-200 rounded-xl">
                <h3 className="text-xl font-bold mb-3 text-blue-700">HRA Exemption</h3>
                <p className="text-gray-700 mb-3">
                  House Rent Allowance (HRA) is partially tax-exempt. You can claim HRA exemption if you live in a rented house. Calculate your HRA tax benefit.
                </p>
                <p className="text-sm text-gray-600">
                  <strong>Calculate:</strong> <Link to="/calculators/hra-calculator" className="text-blue-600 hover:underline">HRA Calculator</Link>
                </p>
              </div>

              <div className="p-6 border-2 border-orange-200 rounded-xl">
                <h3 className="text-xl font-bold mb-3 text-orange-700">PF Benefits</h3>
                <p className="text-gray-700 mb-3">
                  Provident Fund (PF) is a retirement savings scheme. Both you and your employer contribute 12% of your basic salary. It earns 8.1% interest (tax-free).
                </p>
                <p className="text-sm text-gray-600">
                  <strong>Calculate:</strong> <Link to="/calculators/ppf-calculator" className="text-orange-600 hover:underline">PPF Calculator</Link>
                </p>
              </div>
            </div>
          </div>

          {/* Related Calculators */}
          <div className="mt-12 bg-gradient-to-br from-indigo-50 to-purple-50 rounded-2xl shadow-xl p-8">
            <h2 className="text-3xl font-black mb-6">🔗 Related Calculators</h2>
            
            <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-4">
              <Link to="/calculators/income-tax-calculator" className="p-4 bg-white rounded-xl shadow-md hover:shadow-xl hover:scale-105 transition-all">
                <div className="text-4xl mb-2">📄</div>
                <h3 className="font-bold text-gray-900">Income Tax</h3>
                <p className="text-xs text-gray-600">Calculate tax liability</p>
              </Link>

              <Link to="/calculators/hra-calculator" className="p-4 bg-white rounded-xl shadow-md hover:shadow-xl hover:scale-105 transition-all">
                <div className="text-4xl mb-2">🏠</div>
                <h3 className="font-bold text-gray-900">HRA Calculator</h3>
                <p className="text-xs text-gray-600">HRA tax exemption</p>
              </Link>

              <Link to="/calculators/ppf-calculator" className="p-4 bg-white rounded-xl shadow-md hover:shadow-xl hover:scale-105 transition-all">
                <div className="text-4xl mb-2">🏦</div>
                <h3 className="font-bold text-gray-900">PPF Calculator</h3>
                <p className="text-xs text-gray-600">Retirement planning</p>
              </Link>

              <Link to="/calculators/sip-calculator" className="p-4 bg-white rounded-xl shadow-md hover:shadow-xl hover:scale-105 transition-all">
                <div className="text-4xl mb-2">📈</div>
                <h3 className="font-bold text-gray-900">SIP Calculator</h3>
                <p className="text-xs text-gray-600">Investment planning</p>
              </Link>
            </div>
          </div>

          {/* Expert Tips */}
          <div className="mt-12 bg-white rounded-2xl shadow-2xl p-8">
            <h2 className="text-3xl font-black mb-6">💡 Salary Optimization Tips</h2>
            
            <div className="grid md:grid-cols-3 gap-6">
              <div className="p-6 border-l-4 border-green-500 bg-green-50">
                <h3 className="font-bold text-lg mb-2">Maximize Tax Savings</h3>
                <p className="text-gray-700 text-sm">
                  Invest in tax-saving instruments under Section 80C (₹1.5L limit): EPF, PPF, ELSS, NPS to reduce taxable income.
                </p>
              </div>

              <div className="p-6 border-l-4 border-blue-500 bg-blue-50">
                <h3 className="font-bold text-lg mb-2">Optimize Salary Structure</h3>
                <p className="text-gray-700 text-sm">
                  Higher HRA and Special Allowances can reduce tax burden. Discuss with employer for tax-efficient structure.
                </p>
              </div>

              <div className="p-6 border-l-4 border-purple-500 bg-purple-50">
                <h3 className="font-bold text-lg mb-2">Plan Your Investments</h3>
                <p className="text-gray-700 text-sm">
                  Start SIP in mutual funds, build emergency fund (6 months salary), and invest in PPF for retirement.
                </p>
              </div>
            </div>
          </div>

          {/* External Resources */}
          <div className="mt-8 text-center text-sm text-gray-600">
            <p>
              <strong>External Resources:</strong>{' '}
              <a href="https://www.epfindia.gov.in/" target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">EPFO Official</a> •{' '}
              <a href="https://incometaxindia.gov.in/" target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">Income Tax India</a> •{' '}
              <a href="https://www.rbi.org.in/" target="_blank" rel="noopener noreferrer" className="text-indigo-600 hover:underline">RBI</a>
            </p>
          </div>
        </div>
      </div>
    </>
  );
};

export default SalaryCalculator;

