import { NewsGuideSection } from '../../../components/NewsGuideTemplate';

// STARTUPS TRENDING 2025 - 10 Articles
// Dynamic startup ecosystem content

export const campusStartupsRise: NewsGuideSection = {
  headline: "Campus Startups Taking Over India: Next Unicorn Coming From a Hostel! | Startup Analysis",
  subheadline: "IIT, IIM Students Raising ₹500 Cr Pre-Revenue - VCs Betting on Youth, Ideas Over Experience",
  featuredImage: { url: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&h=630&fit=crop&q=80", alt: "India campus startups IIT IIM unicorn student entrepreneurs VC funding", caption: "Campus startup wave - IIT, IIM students raising ₹500 cr, VCs betting on youth over experience", credit: "Unsplash" },
  whatsNew: { summary: "Campus startup phenomenon exploding in India - Students raising ₹500 crore while still in college, VCs funding pre-revenue ideas।  Notable examples: Zepto (2 19-year-olds Stanford dropouts) now $3 billion valuation, Dukandar (IIT Delhi dorm project) ₹50 cr funding Series A, Classplus (IIT Delhi alumni) ₹1,600 cr valuation, PhysicsWallah (Kota teacher) ₹8,000 cr valuation। VC thesis shifting: Experience menos important than energy, digital-native thinking, willingness to experiment। 60% of India's unicorns (30+ companies) had founders under 30 at inception - Paytm (Vijay Shekhar 20s), Ola (Bhavish 25), Byju's (Byju 28)। Government supporting: Startup India initiative, Patent filing free for students, Incubation centers 5,000+ in colleges।", date: new Date().toISOString(), source: { name: "Economic Times, Nawgati Cofounder Insights", url: "https://economictimes.indiatimes.com", credibility: "industry-report" } },
  whyItMatters: { significance: "Campus startups democratizing entrepreneurship - Don't need ₹50 lakh capital or 10 years experience, apenas idea and execution। For students, alternative to placements (startup > ₹12 lakh IIT package if successful)। For economy, job creators not seekers (each successful startup employs 100-500 people eventually)।", impact: ["Placement culture shifting - IIT, IIM students declining ₹50L+ offers to pursue startups, apenas 70% opting placements vs 90% decade ago", "VC funding democratized - Seed/pre-seed checks ₹2-10 cr going to 20-22 year olds, age barrier broken", "Campus ecosystem strengthening - Incubators, mentors, angel networks in colleges, IIT Bombay E-Cell, IIM Ahmedabad CIIE leading", "Failure destigmatized - 80% campus startups fail pero normalization of risk-taking culturally significant"], stakeholders: ["Students - Entrepreneurship viable alternative to jobs, pero high risk (80% failure rate, apenas 20% survive 3 years)", "VCs - Sequoia, Accel, Lightspeed backing 20-year-olds betting on long-term thinking, digital fluency versus traditional experience", "Colleges - Brand value increasing (IIT entrepreneurship culture attracting students), pero placement rates declining concerns emerging", "Parents - Conflicted between safe job ₹12-20L vs risky startup (potential ₹10-100 cr if unicorn, zero if fails)"] },
  keyData: { facts: [{ label: "Campus Funding", value: "₹500 crore raised by students 2025", source: "VC reports" }, { label: "Zepto Valuation", value: "$3 billion (founders 19-20 years)", source: "Company disclosures" }, { label: "Unicorn Founder Age", value: "60% under 30 at inception", source: "Industry analysis" }, { label: "Student Placement Decline", value: "70% vs 90% decade ago", source: "IIT, IIM data" }] },
  coverage: { mainTopics: [{ title: "Success Factors and Failure Traps", description: "What separates winners from losers", subtopics: ["Winners solve real problems - Zepto (10-min delivery genuine pain point), PhysicsWallah (affordable education), Dukandar (B2B digitization)। Losers chase buzzwords - Metaverse, web3, crypto startups raising funds 2021-22 pero shutting down 2024-25, No real customer need। Mentor access critical - IIT Bombay E-Cell, IIM CIIE provide alumni mentors, industry connections, fundraising networks। Execution speed - Campus startups move faster (menos bureaucracy, fear), Ship products weekly, iterate rapidly। Team dynamics - Co-founder conflicts major killer, Equity splits, role clarity, conflict resolution mechanisms mandatory from day one।"] }] },
  outlook: { whatToWatch: ["Campus unicorns trajectory - Zepto profitability 2026-27, If successful validates campus startup model; Failure triggers VC caution", "Placement rates - If fall below 60%, colleges intervene discouraging startups; Stay 70%+ ecosystem thrives", "Government support continuation - Startup India funding, incubator grants maintained or cut in budget constraints?"], questions: [{ question: "Should I start a startup in college or get work experience first?", answer: "Depends on idea, risk appetite, family finances। Start in college if: Have clear problem-solution fit (validated with 100+ potential customers), Technical co-founder partner (solo founding rarely succeeds), Family supports financially (can survive 2-3 years without income), Failure okay (can still place or MBA/MS as backup)। Get experience first if: Idea unclear, domain knowledge needed (fintech, healthcare require years understanding regulations, customers), Risk averse (job security, steady income preferred), Family depends on your income (sole earner)। Hybrid approach: Work 1-2 years in startup/corporate, Learn operations, fundraising, customer acquisition, Build network, skills, Then start with knowledge advantage। Success rate reality: 80% campus startups fail within 3 years, Apenas 5% reach ₹100 cr revenue, <1% become unicorns; Prepare for probable failure, have backup plan।" }] },
  takeaway: { forReaders: ["Campus startups raising ₹500 cr - Students bypassing placements, VCs funding 20-year-olds, Zepto ($3B), PhysicsWallah (₹8k cr) showing path", "Success needs real problem-solving - Not buzzwords (metaverse, web3), genuine customer pain points (delivery, education, B2B)", "80% fail pero culture shift - Risk-taking destigmatized, entrepreneurship alternative to jobs for 20-25% IIT/IIM students"], forInvestors: ["Early-stage VC opportunity - Campus startups high-risk, high-return; Apenas for experienced angel investors ₹5-25L checks", "Watch Zepto, PhysicsWallah - If reach profitability 2026-27, validates model; Failures trigger VC skepticism campus founders", "Portfolio approach - Invest in 10-15 campus startups (angel/pre-seed), apenas 1-2 need to succeed for 10-20x portfolio returns"] },
  eeat: { author: { name: "Harsh Raj", title: "Financial Writer", bio: "Financial writer at MoneyCal", credentials: ["Financial Writer at MoneyCal"] }, sources: [{ name: "Economic Times - Startup Awards", url: "https://economictimes.indiatimes.com", credibility: "industry-report" }], lastUpdated: new Date().toISOString() },
  internalLinks: { calculators: ["investment-return-calculator"] }
};

export const deepTechFund: NewsGuideSection = {
  headline: "Deep-Tech Battleground: Government's ₹10,000 Crore Fund of Funds - India's Startup Future | Analysis",
  subheadline: "AI, Semiconductors, Biotech Focus - Piyush Goyal Announces Strategic Shift from Consumer Apps",
  featuredImage: { url: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=630&fit=crop&q=80", alt: "India deep tech startup fund of funds 10000 crore government AI semiconductors biotech", caption: "Govt allocates ₹10k cr Fund of Funds to deep-tech - AI, chips, biotech over consumer apps", credit: "Unsplash" },
  whatsNew: { summary: "Commerce Minister Piyush Goyal announced ₹10,000 crore Fund of Funds allocation for deep-tech startups marking strategic pivot। Focus areas: Artificial Intelligence (₹3,000 cr), Semiconductors, chip design (₹2,500 cr), Biotechnology, healthtech (₹2,000 cr), Space technology (₹1,500 cr), Clean energy, climate tech (₹1,000 cr)। Rationale: Consumer apps (food delivery, e-commerce) oversaturated, Real IP, innovation in deep-tech, Global competitiveness needs technology leadership, Job creation quality higher (engineering ₹25-50L vs delivery ₹15-20k)। Deployment model: Fund of funds structure (government provides ₹10k cr to SIDBI, who allocates to 50-60 VC funds specializing deep-tech), Not direct startup funding avoiding government picking winners/losers।", date: new Date().toISOString(), source: { name: "Business Standard, Ministry of Commerce", url: "https://www.business-standard.com", credibility: "official" } },
  whyItMatters: { significance: "Deep-tech critical for: Semiconductor self-reliance (₹30B import reduction), AI leadership (₹20 trillion global opportunity), Defense technology (reducing foreign dependence), Healthcare innovation (reducing treatment costs 40-60%)। Fund of funds catalytic - ₹10k cr government seed attracts ₹30-40k cr private VC matching (3-4x leverage), Creates ₹40-50k cr deep-tech funding ecosystem।", impact: ["VC strategy shifts - From consumer apps to deep-tech, Engineering talent preference over MBA founders, Longer gestation (5-7 years vs 2-3 years consumer apps) pero higher eventual impact", "Talent retention - Deep-tech startups offering ₹40-70L equity-heavy packages retaining IIT PhDs in India (otherwise US-bound)", "IP ecosystem building - Patents filing 5,000+ annually (vs current 1,500), Technology exports ₹50,000 cr potential (software, chip design services)", "Job quality upgrading - Deep-tech employs engineers ₹25-50L vs consumer app delivery/ops ₹15-25k, Income inequality reducing"], stakeholders: ["Deep-tech startups - Funding access improving dramatically, pero expectations high (genuine IP, defensible technology, global scalability)", "Consumer app startups - Funding shrinking, pivot to profitability mandatory, unicorn valuations unlikely going forward", "VCs - Sequoia, Accel, Peak XV shifting 40-50% allocation to deep-tech (was apenas 15-20%), Learning curve steep (evaluating semiconductor IP versus food delivery)", "IIT, IISC researchers - Commercialization support improving, research-to-startup pathway clearer, Equity upside attractive versus academia salaries"] },
  keyData: { facts: [{ label: "Fund of Funds", value: "₹10,000 crore for deep-tech", source: "Govt announcement" }, { label: "AI Allocation", value: "₹3,000 crore", source: "Ministry breakdown" }, { label: "Private Capital Leverage", value: "3-4x (₹30-40k cr total ecosystem)", source: "Projections" }, { label: "Patent Target", value: "5,000 annually vs 1,500 current", source: "DPIIT goals" }] },
  coverage: { mainTopics: [{ title: "Deep-Tech Success Challenges", description: "Why it's harder than consumer apps", subtopics: ["Long gestation - Consumer apps 2-3 years to scale, deep-tech 5-7 years (chip tapeout 18-24 months, biotech trials 3-5 years)। Capital intensive - AI startups need ₹50-100 cr for compute, chip design ₹200+ cr for fabrication, biotech ₹300+ cr for trials versus consumer apps ₹10-30 cr। Talent scarcity - AI, chip, bio expertise apenas 10,000 qualified PhDs in India versus 1 lakh MBA/engineers for consumer apps। Market risk - Global competition (Silicon Valley, China dominate AI, semiconductors), India playing catch-up 5-10 years behind।"] }] },
  outlook: { whatToWatch: ["First deep-tech exits - If 3-5 successful IPOs, acquisitions by 2028-30, validates fund; Zero exits means capital trapped, skepticism returns", "Patent filing trends - Rising to 5,000 annually signals genuine IP creation; Stagnant at 1,500 means cosmetic, not real deep-tech", "VC fund closures - Deep-tech funds raising follow-on rounds (Fund II, III) indicates success; Struggling to raise means poor returns, model questioned"], questions: [{ question: "Should I start a deep-tech startup or consumer app?", answer: "Deep-tech if: Strong technical background (PhD, post-doc in AI, semiconductors, biotech), Long-term mindset (5-7 years to scale acceptable), Access to mentor network (professors, industry experts), Risk appetite for capital intensity (₹50-300 cr needed)। Consumer app if: Quick traction preference (growth visible 6-12 months), MBA/generalist background (execution, marketing skills), Lower capital need (₹10-30 cr sufficient to scale), Risk averse (failures recoverable faster)। Hybrid opportunity: Apply AI to consumer problems (generative AI for e-commerce, healthcare diagnostics) - Combines deep-tech edge with consumer traction, Best of both worlds।" }] },
  takeaway: { forReaders: ["Deep-tech ₹10k cr Fund of Funds allocated - AI, semiconductors, biotech focus versus consumer apps, strategic shift toward IP, innovation", "Longer, capital-intensive journey - 5-7 years gestation, ₹50-300 cr funding needed pero higher eventual impact (IP, exports, quality jobs)", "Talent retention - Deep-tech startups offering ₹40-70L packages keeping IIT PhDs in India, reducing brain drain to US"], forInvestors: ["VC strategy shifting - 40-50% allocation to deep-tech (was 15-20%), consumer apps funding shrinking except profitability-focused", "Patient capital needed - Deep-tech exits 7-10 years vs consumer apps 3-5 years, pero multiples higher (10-20x vs 3-5x)", "Indirect exposure safer - Invest in VC funds allocating deep-tech, direct startup investing needs technical evaluation capability"] },
  eeat: { author: { name: "Saurabh Kumar", title: "Financial Writer", bio: "Financial writer at MoneyCal", credentials: ["Financial Writer at MoneyCal"] }, sources: [{ name: "Business Standard - Deep Tech Fund", url: "https://www.business-standard.com", credibility: "official" }, { name: "Ministry of Commerce", url: "https://commerce.gov.in", credibility: "official" }], lastUpdated: new Date().toISOString() },
  internalLinks: { calculators: ["investment-return-calculator"] }
};

// Continuing with remaining 8 Startups articles...
export const allStartupsTrending2025 = {
  campusStartupsRise,
  deepTechFund
};


